import {timeline,subtitles}from'./timeline';
import {spawn} from 'node:child_process';import {mkdir,writeFile}from'node:fs/promises';import path from'node:path';
export const videoPath=(userId:string,id:string)=>path.join(process.env.CORA_DATA_DIR||path.join(process.cwd(),'data','cora'),'videos',userId,id);
export async function renderVideo(userId:string,id:string,frames:string[],seconds:number,sceneInput?:unknown){
 const scenes=timeline(frames.length,sceneInput,seconds);const total=scenes.reduce((sum,s)=>sum+s.seconds,0);const srt=subtitles(scenes);
 const dir=videoPath(userId,id);await mkdir(dir,{recursive:true});for(const [i,f]of frames.entries()){if(typeof f!=='string'||f.length>800000||!/^data:image\/png;base64,[A-Za-z0-9+/=]+$/.test(f))throw new Error('PNG 장면 형식을 확인해 주세요.');const data=Buffer.from(f.split(',')[1],'base64');if(data.subarray(0,8).toString('hex')!=='89504e470d0a1a0a')throw new Error('올바른 PNG가 아닙니다.');await writeFile(path.join(dir,`frame-${String(i).padStart(2,'0')}.png`),data);}
 await writeFile(path.join(dir,'timeline.txt'),scenes.map((s,i)=>`file 'frame-${String(i).padStart(2,'0')}.png'\nduration ${s.seconds}\n`).join('')+`file 'frame-${String(frames.length-1).padStart(2,'0')}.png'\n`);
 if(srt)await writeFile(path.join(dir,'subtitles.srt'),srt);
 await new Promise<void>((resolve,reject)=>{const p=spawn(process.env.CORA_FFMPEG||'ffmpeg',['-y','-f','concat','-safe','1','-i',path.join(dir,'timeline.txt'),...(srt?['-i',path.join(dir,'subtitles.srt'),'-map','0:v:0','-map','1:s:0','-c:s','mov_text','-metadata:s:s:0','language=kor']:[]),'-vf','scale=1080:1920:force_original_aspect_ratio=decrease,pad=1080:1920:(ow-iw)/2:(oh-ih)/2:color=0x183e33,fps=24,tpad=stop_mode=clone:stop_duration=1','-t',String(total),'-r','24','-c:v','libx264','-preset','ultrafast','-crf','24','-pix_fmt','yuv420p','-movflags','+faststart',path.join(dir,'video.mp4')],{stdio:['ignore','ignore','pipe']});const timer=setTimeout(()=>{p.kill('SIGKILL');reject(new Error('렌더 시간 초과'));},120000);p.stderr.on('data',()=>{});p.on('error',()=>{clearTimeout(timer);reject(new Error('FFmpeg 설치 경로를 확인해 주세요.'));});p.on('close',code=>{clearTimeout(timer);code===0?resolve():reject(new Error('MP4 렌더에 실패했습니다.'));});});
 return{status:'ready',seconds:total,frames:frames.length,width:1080,height:1920,audio:false,subtitles:!!srt,scenes};
}
