'use client';
import {useEffect,useState} from 'react';
import type {Client,ClientInput,AccessibleClient,ClientRevision} from '@/lib/cora/clients';
import s from './workbench.module.css';
const empty:ClientInput={name:'',audience:'',goal:'',voice:'',visualRules:'',pillars:'',avoid:'',accent:'#205b4a'};
export function ClientDesk({clients,onSaved,onCreate}:{clients:AccessibleClient[];onSaved:(client:Client)=>void;onCreate:(client:Client)=>void}){
 const [history,setHistory]=useState<ClientRevision[]>([]);
 const [editing,setEditing]=useState<Client|null>(null),[form,setForm]=useState<ClientInput>({...empty}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const readOnly=!!editing&&clients.find(c=>c.id===editing.id)?.access==='editor';
 useEffect(()=>{let active=true;setHistory([]);if(editing)void fetch('/api/cora/clients?'+new URLSearchParams({id:editing.id})).then(async r=>{const v=await r.json();if(!r.ok)throw new Error(v.error);if(active)setHistory(v.history);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[editing?.id,editing?.version]);
 async function save(){setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/cora/clients',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,...(editing?{id:editing.id,version:editing.version}:{})})});const v=await r.json();if(!r.ok)throw new Error(v.error);onSaved(v.client);setEditing(v.client);setForm({...v.client,changeNote:''});setNotice('고객사 맥락을 저장했습니다.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className={s.root}><h1>고객사</h1><p>고객사의 주제와 말투를 저장하고 제작에 적용하세요. 같은 이름도 각각 별도 고객사로 관리됩니다.</p>
 {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<div className={s.grid}>
 <section className={s.panel}><h2>관리 중인 고객사</h2><button onClick={()=>{setEditing(null);setForm({...empty});setNotice('');}}>새 고객사</button>{clients.map(c=><article className={s.row} key={c.id}><h3>{c.name}</h3><small>고객사 {c.id.slice(0,8)} · v{c.version}</small><p>{c.audience} · {c.goal}</p>{c.access==='editor'?<><p>팀 고객사 · {c.ownerEmail} · 맥락 수정은 소유자만 가능합니다.</p><button onClick={()=>{setEditing(c);setForm({...c,changeNote:''});}}>규칙 이력 보기</button></>:<button onClick={()=>{setEditing(c);setForm({...c,changeNote:''});setNotice('');}}>맥락 수정</button>}<button onClick={()=>onCreate(c)}>이 고객사 콘텐츠 만들기</button></article>)}{!clients.length&&<p>첫 고객사를 등록해 주세요.</p>}</section>
 <section className={s.panel}><h2>{editing?'고객사 맥락 수정':'고객사 등록'}</h2><fieldset disabled={busy||readOnly}>
 {([['name','고객사 이름',80],['audience','주요 고객',160],['goal','콘텐츠 목표',200],['voice','말투와 문장 예시',2000],['visualRules','시각 규칙',2000],['pillars','반복할 주제',2000],['avoid','피할 표현',2000],['ruleEvidence','규칙의 근거·참고 자료',1000],['changeNote','이번 수정 이유·다음 제작에 반영할 메모',500]] as const).map(([key,label,max])=><label key={key}>{label}<textarea aria-label={label} rows={key==='name'?1:2} maxLength={max} value={form[key]??''} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}
 <label>고객사 색상<input aria-label="고객사 색상" type="color" value={form.accent} onChange={e=>setForm({...form,accent:e.target.value})}/></label><button className={s.primary} disabled={!form.name.trim()} onClick={()=>void save()}>{busy?'저장 중…':'고객사 저장'}</button>
 </fieldset><p>말투·시각 규칙·주제·피할 표현은 일반 콘텐츠와 광고 제작이 함께 참조합니다. 수정 메모는 최근 5개를 다음 AI 제작 지시에 반영합니다. 근거는 사용자가 확인한 자료 메모입니다.</p>
 {editing&&<section><h3>브랜드 규칙 수정 이력</h3><p>최근 100개 버전을 표시합니다. 과거 규칙을 불러와 저장하면 새 버전이며 기존 콘텐츠는 바뀌지 않습니다.</p>{history.map(r=><details key={r.version}><summary>v{r.version} · {r.confirmedAt} · {r.imported?'기존 자료 이전':`확인자 ${r.authorId.slice(0,8)}`}</summary><p>변경: {r.changedFields.join(', ')||'당시 변경 항목 기록 없음'}</p><p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>근거: {r.client.ruleEvidence||'미기록'}<br/>수정 메모: {r.client.changeNote||'미기록'}</p><dl>{Object.entries(r.client).map(([k,v])=><div key={k}><dt>{k}</dt><dd style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{v}</dd></div>)}</dl>{!readOnly&&<button disabled={busy} onClick={()=>{setForm({...r.client,changeNote:`v${r.version} 규칙을 검토하여 다시 적용`});setNotice('과거 규칙을 입력란으로 가져왔습니다. 검토 후 저장하면 새 버전입니다.');}}>이 규칙을 불러와 새 버전으로 수정</button>}</details>)}</section>}</section></div></div>;
}

