'use client';
import{useState,useEffect,useCallback}from'react';import s from'./workbench.module.css';
type Design={ratio:'4:5'|'1:1'|'9:16';template:'editorial'|'minimal'|'bold';font:'sans'|'serif';textScale:number};
type Tpl={id:string;name:string;source:'project'|'builtin';design:Design;styles:unknown[];slideCount:number;favorite:boolean;version:number};
type Logo={id:string;name:string;brand:string;data:string;isDefault:boolean};
type Cta={id:string;text:string;brand:string;uses:number};
type Builtin={id:string;name:string;design:Design};
type View={templates:Tpl[];logos:Logo[];ctas:Cta[];builtins:Builtin[]};
type Proj={id:string;title:string;brand:string};
const tplLabel={editorial:'에디토리얼',minimal:'미니멀',bold:'볼드'};
async function api(data?:Record<string,unknown>,query=''):Promise<View>{const r=await fetch('/api/cora/library'+query,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json'}:undefined,body:data?JSON.stringify(data):undefined});const v=await r.json();if(!r.ok)throw new Error(v.error);return v;}
/** Asset library: personal card templates (favorite, copy built-ins, edit), brand logos (max 5), reusable CTA phrases. */
export function LibraryDesk({onApply}:{onApply?:(templateId:string)=>void}){
 const[data,setData]=useState<View|null>(null),[projects,setProjects]=useState<Proj[]>([]),[projectId,setProjectId]=useState(''),[name,setName]=useState(''),[editing,setEditing]=useState<{id:string;version:number;name:string;design:Design}|null>(null),[logoName,setLogoName]=useState(''),[logoBrand,setLogoBrand]=useState(''),[logoData,setLogoData]=useState(''),[cta,setCta]=useState(''),[ctaBrand,setCtaBrand]=useState(''),[filter,setFilter]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const refresh=useCallback(async()=>setData(await api()),[]);
 useEffect(()=>{void refresh().catch(e=>setError(e.message));void fetch('/api/cora/projects').then(r=>r.json()).then(v=>{const list=(v.projects||[]) as Proj[];setProjects(list);if(list[0])setProjectId(list[0].id);}).catch(()=>{});},[refresh]);
 async function run(f:()=>Promise<View|void>,msg:string){if(busy)return;setBusy(true);setError('');setNotice('');try{const v=await f();if(v)setData(v);setNotice(msg);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function pick(file?:File){setLogoData('');if(!file)return;if(!/^image\/(png|jpeg|webp)$/.test(file.type)||file.size>300000){setError('로고는 300KB 이하의 PNG, JPEG, WebP 이미지여야 합니다.');return;}const r=new FileReader();r.onload=()=>setLogoData(String(r.result));r.readAsDataURL(file);}
 const shown=data?.ctas.filter(c=>!filter||c.brand===filter)||[],brands=[...new Set((data?.ctas||[]).map(c=>c.brand).filter(Boolean))];
 return <div className={s.root}><h1>자산 라이브러리</h1><p className={s.warning}>템플릿, 로고, CTA 문구는 내 계정에만 저장되며 다른 계정에서는 보이지 않습니다.</p>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
  <div className={s.grid}><section className={s.panel}><h2>템플릿</h2><p>저장한 작업의 디자인과 카드별 문자·사진 설정을 템플릿으로 보관합니다. 기본 디자인 3종은 내 템플릿으로 복사한 뒤 고칠 수 있습니다.</p>
   <label>템플릿으로 저장할 작업<select aria-label="템플릿으로 저장할 작업" value={projectId} onChange={e=>setProjectId(e.target.value)}>{projects.map(p=><option key={p.id} value={p.id}>{p.brand} · {p.title}</option>)}</select></label>
   <label>템플릿 이름<input aria-label="템플릿 이름" maxLength={60} value={name} onChange={e=>setName(e.target.value)}/></label>
   <button className={s.primary} disabled={busy||!projectId||!name.trim()} onClick={()=>void run(async()=>{const v=await api({action:'save-template',projectId,name});setName('');return v;},'템플릿으로 저장했습니다.')}>작업을 템플릿으로 저장</button>
   <h3>기본 디자인 복사</h3><div className={s.actions}>{data?.builtins.map(b=><button key={b.id} disabled={busy} onClick={()=>void run(()=>api({action:'save-template',builtin:b.id}),`${b.name} 디자인을 내 템플릿으로 복사했습니다.`)}>{b.name} 복사</button>)}</div>
   {data?.templates.map(t=><article className={s.row} key={t.id}><small>{t.favorite?'★ 즐겨찾기 · ':''}{t.source==='builtin'?'기본 디자인 복사':'작업에서 저장'} · {tplLabel[t.design.template]} · {t.design.ratio} · {t.design.font==='serif'?'명조':'고딕'} · v{t.version}</small><h3>{t.name}</h3>
    {editing?.id===t.id?<div><label>이름<input aria-label="템플릿 이름 수정" maxLength={60} value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><label>디자인<select aria-label="디자인 수정" value={editing.design.template} onChange={e=>setEditing({...editing,design:{...editing.design,template:e.target.value as Design['template']}})}><option value="editorial">에디토리얼</option><option value="minimal">미니멀</option><option value="bold">볼드</option></select></label><label>글꼴<select aria-label="글꼴 수정" value={editing.design.font} onChange={e=>setEditing({...editing,design:{...editing.design,font:e.target.value as Design['font']}})}><option value="sans">고딕</option><option value="serif">명조</option></select></label>
     <div className={s.actions}><button className={s.primary} disabled={busy||!editing.name.trim()} onClick={()=>void run(async()=>{const v=await api({action:'update-template',id:t.id,version:editing.version,name:editing.name,design:editing.design});setEditing(null);return v;},'템플릿을 수정했습니다.')}>수정 저장</button><button onClick={()=>setEditing(null)}>취소</button></div></div>
     :<div className={s.actions}><button disabled={busy} onClick={()=>void run(()=>api({action:'favorite',id:t.id,favorite:!t.favorite}),t.favorite?'즐겨찾기를 해제했습니다.':'즐겨찾기에 추가했습니다.')}>{t.favorite?'즐겨찾기 해제':'즐겨찾기'}</button>{onApply&&<button className={s.primary} disabled={busy} onClick={()=>onApply(t.id)}>이 템플릿 적용</button>}<button disabled={busy} onClick={()=>setEditing({id:t.id,version:t.version,name:t.name,design:t.design})}>수정</button><button className={s.danger} disabled={busy} onClick={()=>{if(window.confirm(`템플릿 "${t.name}"을 삭제할까요?`))void run(()=>api({action:'delete-template',id:t.id}),'템플릿을 삭제했습니다.');}}>삭제</button></div>}</article>)}{!data?.templates.length&&<p>보관한 템플릿이 없습니다.</p>}</section>
  <section className={s.panel}><h2>로고</h2><p>로고는 계정당 5개까지 보관합니다. PNG, JPEG, WebP 형식이며 브랜드마다 기본 로고를 하나 정할 수 있습니다.</p>
   <label>로고 이름<input aria-label="로고 이름" maxLength={60} value={logoName} onChange={e=>setLogoName(e.target.value)}/></label><label>브랜드 이름(선택)<input aria-label="로고 브랜드" maxLength={80} value={logoBrand} onChange={e=>setLogoBrand(e.target.value)}/></label><label>로고 파일<input aria-label="로고 파일" type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>pick(e.target.files?.[0])}/></label>
   <button className={s.primary} disabled={busy||!logoName.trim()||!logoData} onClick={()=>void run(async()=>{const v=await api({action:'add-logo',name:logoName,brand:logoBrand,data:logoData});setLogoName('');setLogoData('');return v;},'로고를 저장했습니다.')}>로고 추가</button>
   {data?.logos.map(l=><article className={s.row} key={l.id}><small>{l.brand||'브랜드 미지정'}{l.isDefault?' · 기본 로고':''}</small><h3>{l.name}</h3>{/* eslint-disable-next-line @next/next/no-img-element */}<img src={l.data} alt={`로고 ${l.name}`} style={{maxWidth:120,maxHeight:80}}/><div className={s.actions}>{!l.isDefault&&<button disabled={busy} onClick={()=>void run(()=>api({action:'set-default-logo',id:l.id}),'기본 로고를 바꿨습니다.')}>기본 로고로 지정</button>}<button className={s.danger} disabled={busy} onClick={()=>{if(window.confirm(`로고 "${l.name}"을 삭제할까요?`))void run(()=>api({action:'delete-logo',id:l.id}),'로고를 삭제했습니다.');}}>삭제</button></div></article>)}{!data?.logos.length&&<p>보관한 로고가 없습니다.</p>}</section></div>
  <div className={s.grid}><section className={s.panel}><h2>CTA 문구</h2><p>행동을 안내하는 문구를 200자 이내로 보관합니다. 사용을 누르면 문구를 클립보드에 복사하고 사용 횟수를 1 올립니다.</p>
   <label>CTA 문구<textarea aria-label="CTA 문구" maxLength={200} value={cta} onChange={e=>setCta(e.target.value)}/></label><label>브랜드 이름(선택)<input aria-label="CTA 브랜드" maxLength={80} value={ctaBrand} onChange={e=>setCtaBrand(e.target.value)}/></label>
   <button className={s.primary} disabled={busy||!cta.trim()} onClick={()=>void run(async()=>{const v=await api({action:'add-cta',text:cta,brand:ctaBrand});setCta('');return v;},'CTA 문구를 저장했습니다.')}>문구 저장</button></section>
  <section className={s.panel}><h2>저장한 CTA 문구</h2><label>브랜드 필터<select aria-label="CTA 브랜드 필터" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">전체 브랜드</option>{brands.map(b=><option key={b} value={b}>{b}</option>)}</select></label>
   {shown.map(c=><article className={s.row} key={c.id}><small>{c.brand||'브랜드 미지정'} · 사용 {c.uses}회</small><p>{c.text}</p><div className={s.actions}><button disabled={busy} onClick={()=>void run(async()=>{const v=await api({action:'use-cta',id:c.id});try{await navigator.clipboard.writeText(c.text);}catch{}return v;},'문구를 복사하고 사용 횟수를 올렸습니다.')}>사용</button><button className={s.danger} disabled={busy} onClick={()=>void run(()=>api({action:'delete-cta',id:c.id}),'문구를 삭제했습니다.')}>삭제</button></div></article>)}{!shown.length&&<p>저장한 CTA 문구가 없습니다.</p>}</section></div></div>;
}
