'use client';
import{useState,useEffect}from'react';import s from'./workbench.module.css';
type Job={id:string;version:number;currentVersion:number;accountLabel:string;scheduledAt:string;status:string;effectiveStatus:string;title:string;brand:string;caption:string};
type Approval={id:string;owner_id:string;effectiveStatus:string;version:number;brand?:string;title?:string};
type Simulation={id:string;draft_id:string|null;state:string;attempts:number};
const simLabel:Record<string,string>={queued:'실행 대기',submitting:'모의 접수 중',submitted:'모의 접수됨',scheduled:'모의 예약됨',published:'모의 완료 (실제 게시 아님)',failed:'모의 실패',unknown:'결과 불명 · 재전송 안 함',blocked:'승인 변경으로 중단',cancelled:'취소됨'};
const label:Record<string,string>={awaiting_connection:'계정·미디어 연결 대기',needs_review:'재검토 필요',cancelled:'취소됨'};
export function PublicationDesk({userId}:{userId:string}){
 const[simulations,setSimulations]=useState<Simulation[]>([]);
 const[jobs,setJobs]=useState<Job[]>([]),[approvals,setApprovals]=useState<Approval[]>([]),[reviewId,setReviewId]=useState(''),[account,setAccount]=useState(''),[time,setTime]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function api(data?:Record<string,unknown>){const r=await fetch('/api/cora/publications',{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json'}:undefined,body:data?JSON.stringify(data):undefined});const v=await r.json();if(!r.ok)throw new Error(v.error);return v;}
 async function simulation(data?:Record<string,unknown>){const r=await fetch('/api/cora/publications/simulation',{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json'}:undefined,body:data?JSON.stringify(data):undefined});const v=await r.json();if(!r.ok)throw new Error(v.error);return v;}
 async function refresh(){const[pub,res]=await Promise.all([api(),fetch('/api/cora/reviews')]);if(!res.ok)throw new Error('검토 목록을 불러오지 못했습니다.');const reviews=await res.json();setJobs(pub.publications);setSimulations((await simulation()).jobs);setApprovals(reviews.reviews.filter((r:Approval)=>r.owner_id===userId&&r.effectiveStatus==='approved'));}
 useEffect(()=>{void refresh().catch(e=>setError(e.message));},[]);
 async function run(f:()=>Promise<void>){if(busy)return;setBusy(true);setError('');setNotice('');try{await f();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className={s.root}><h1>게시 준비함</h1><p className={s.warning}>현재 실제 SNS 계정 연결·전송은 없습니다. 승인한 콘텐츠 버전과 게시 의도를 저장합니다. 예정 시각을 적어도 자동 게시되지 않습니다.</p>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<button disabled={busy} onClick={()=>void run(refresh)}>게시 준비 새로고침</button><div className={s.grid}><section className={s.panel}><h2>승인한 콘텐츠로 준비</h2><label>승인된 저장 버전<select aria-label="승인된 저장 버전" value={reviewId} onChange={e=>setReviewId(e.target.value)}><option value="">검토자가 승인한 콘텐츠 선택</option>{approvals.map(r=><option key={r.id} value={r.id}>{r.brand} · {r.title} · v{r.version}</option>)}</select></label><label>게시 대상 계정 메모<input aria-label="게시 대상 계정 메모" maxLength={100} value={account} onChange={e=>setAccount(e.target.value)} placeholder="예: 책방 Instagram (연결 전 메모)"/></label><label>희망 게시 시각<input aria-label="희망 게시 시각" type="datetime-local" value={time} onChange={e=>setTime(e.target.value)}/></label><p>시각은 현재 기기의 시간대로 입력하며 UTC로 저장합니다. 빈칸이면 시각 미정입니다. 계정 메모는 실제 SNS 계정 ID가 아닙니다.</p><button disabled={busy||!reviewId||!account.trim()} className={s.primary} onClick={()=>void run(async()=>{await api({action:'prepare',reviewId,accountLabel:account,scheduledAt:time?new Date(time).toISOString():''});await refresh();setNotice('승인 버전으로 게시 준비를 저장했습니다. 외부 전송은 하지 않았습니다.');})}>승인본으로 게시 준비 저장</button>{!approvals.length&&<p>먼저 작업을 저장하고 다른 계정의 검토 승인을 받아 주세요.</p>}</section><section className={s.panel}><h2>저장한 게시 준비</h2>{jobs.map(j=><article className={s.row} key={j.id}><h3>{j.brand} · v{j.version}</h3><p>{label[j.effectiveStatus]} · 현재 원본 v{j.currentVersion}</p><p>{j.accountLabel} · {j.scheduledAt?new Date(j.scheduledAt).toLocaleString('ko-KR'):'시각 미정'}</p><p style={{whiteSpace:'pre-wrap'}}>{j.caption}</p>{j.effectiveStatus==='awaiting_connection'&&<button disabled={busy} onClick={()=>void run(async()=>{await simulation({action:'enqueue',id:j.id});await refresh();setNotice('외부 전송 없는 모의 큐에 등록했습니다.');})}>모의 큐 등록</button>}{j.status==='awaiting_connection'&&<button disabled={busy} onClick={()=>void run(async()=>{await api({action:'cancel',id:j.id});await refresh();setNotice('게시 준비를 취소했습니다. 외부 전송은 없습니다.');})}>게시 준비 취소</button>}</article>)}{!jobs.length&&<p>준비한 게시 작업이 없습니다.</p>}</section></div><section className={s.panel}><h2>게시 흐름 모의 실행</h2><p>네트워크 호출 없이 접수와 결과 대조를 시험합니다. 실제 자동 게시 기능이 아닙니다. 단계 실행 버튼으로 진행하며, 접수 후 결과 조회는 10초 간격입니다.</p>{simulations.map(j=><article className={s.row} key={j.id}><p>{simLabel[j.state]} · 모의 전송 시도 {j.attempts}회</p><button disabled={busy} onClick={()=>void run(async()=>{await simulation({action:'tick',id:j.id});await refresh();})}>모의 단계 실행</button>{j.state==='queued'&&<button disabled={busy} onClick={()=>void run(async()=>{await simulation({action:'cancel',id:j.id});await refresh();})}>모의 작업 취소</button>}</article>)}</section></div>;
}
