'use client';
import{useEffect,useState}from'react';import type{Project}from'@/lib/cora/model';import{artwork}from'@/lib/cora/artwork';import s from'./workbench.module.css';
type Review={brand?:string;title?:string;id:string;project_id:string;owner_id:string;reviewer_id:string;version:number;current_version:number;status:string;effectiveStatus:string;comment:string;owner_email:string;reviewer_email:string;snapshot?:Project};
const labels:Record<string,string>={pending:'검토 대기',approved:'이 버전 승인',changes_requested:'수정 요청',stale:'새 버전 · 재검토 필요',cancelled:'공유 회수'};
export function ReviewInbox({userId}:{userId:string}){
 const[items,setItems]=useState<Review[]>([]),[selected,setSelected]=useState<Review|null>(null),[comment,setComment]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function api(data?:Record<string,unknown>,id?:string){const r=await fetch('/api/cora/reviews'+(id?'?id='+encodeURIComponent(id):''),{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json'}:undefined,body:data?JSON.stringify(data):undefined});const v=await r.json();if(!r.ok)throw new Error(v.error);return v;}
 async function refresh(){setItems((await api()).reviews);}
 async function run(f:()=>Promise<void>){if(busy)return;setBusy(true);setError('');try{await f();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{void refresh().catch(e=>setError(e.message));},[]);
 async function open(id:string){setSelected(null);const r=(await api(undefined,id)).review;setSelected(r);setComment(r.comment);}
 return <div className={s.root}><h1>콘텐츠 검토함</h1><p>요청한 저장 버전의 카드·캡션·원문 자료를 공유합니다. 검토자는 원본을 직접 수정할 수 없습니다. 이메일은 발송하지 않습니다.</p>{error&&<p role="alert">{error}</p>}<button disabled={busy} onClick={()=>void run(async()=>{await refresh();if(selected)await open(selected.id);})}>검토 목록 새로고침</button><div className={s.grid}><section className={s.panel}><h2>보낸 요청 · 받은 요청</h2>{items.map(r=><article className={s.row} key={r.id}><h3>{r.brand} · {r.title}</h3><p>{r.owner_id===userId?'보낸 요청':'받은 요청'} · v{r.version} · {labels[r.effectiveStatus]}</p><small>{r.owner_email} → {r.reviewer_email}</small><button disabled={busy} onClick={()=>void run(()=>open(r.id))}>검토 열기</button></article>)}{!items.length&&<p>검토 요청이 없습니다. 제작실에서 작업을 저장한 뒤 검토자를 지정하세요.</p>}</section><section className={s.panel}>{selected?.snapshot?<><h2>{selected.snapshot.brief.brand} · 저장본 v{selected.version}</h2><p role="status">{labels[selected.effectiveStatus]} · 현재 원본 v{selected.current_version}</p>{selected.effectiveStatus==='stale'&&<p>원본이 변경되어 이 요청으로 승인할 수 없습니다. 제작자가 새 버전으로 다시 요청해야 합니다.</p>}<div>{selected.snapshot.slides.map((slide,i)=><img key={slide.id} src={artwork(slide,selected.snapshot!,i).url} alt={`검토 카드 ${i+1}`} style={{width:'45%',height:'auto',margin:'2%'}}/>)}</div><h3>게시 캡션</h3><p style={{whiteSpace:'pre-wrap'}}>{selected.snapshot.caption}</p><details><summary>공유된 근거 자료</summary><p style={{whiteSpace:'pre-wrap'}}>{selected.snapshot.brief.material}</p><p>{selected.snapshot.brief.sourceUrl}</p></details><p>검토 의견: {selected.comment||'아직 없음'}</p>{selected.reviewer_id===userId&&selected.effectiveStatus==='pending'&&<><label>검토 의견<textarea aria-label="검토 의견" rows={4} maxLength={3000} value={comment} onChange={e=>setComment(e.target.value)}/></label>{[['approved','이 버전 승인'],['changes_requested','수정 요청']].map(([status,title])=><button disabled={busy} key={status} onClick={()=>void run(async()=>{const r=await api({action:'decide',id:selected.id,status,comment});setSelected(r.review);await refresh();})}>{title}</button>)}</>}{selected.owner_id===userId&&selected.status!=='cancelled'&&<button disabled={busy} onClick={()=>{if(window.confirm('검토자의 접근을 회수할까요?'))void run(async()=>{await api({action:'cancel',id:selected.id});await open(selected.id);await refresh();});}}>검토 공유 회수</button>}</>:<p>요청을 열면 공유한 버전의 실제 카드와 캡션이 표시됩니다.</p>}</section></div></div>;
}
