'use client';
import{useState,useEffect,useCallback}from'react';import s from'./workbench.module.css';
type Member={id:string;role:'editor'|'reviewer';brands:string[];status:string;ownerEmail:string;memberEmail:string};
type Shared={id:string;brand:string;title:string;count:number;version:number;updatedAt:string;ownerEmail:string};
type View={members:Member[];memberships:Member[];sharedProjects:Shared[];reviewerSuggestions:string[];brands:string[]};
const roleLabel={editor:'편집자',reviewer:'검토자'};
const statusLabel:Record<string,string>={invited:'수락 대기',active:'참여 중',declined:'거절함'};
async function api(data?:Record<string,unknown>):Promise<View>{const r=await fetch('/api/cora/team',{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json'}:undefined,body:data?JSON.stringify(data):undefined});const v=await r.json();if(!r.ok)throw new Error(v.error);return v;}
const brandText=(b:string[])=>b.length?b.join(', '):'전체 브랜드';
/** Workspace team: invite by existing account email, accept/decline, change role and brand scope, remove/leave, open shared work. */
export function TeamDesk({onOpen}:{onOpen:(id:string)=>void}){
 const[data,setData]=useState<View|null>(null),[email,setEmail]=useState(''),[role,setRole]=useState<'editor'|'reviewer'>('editor'),[brands,setBrands]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const refresh=useCallback(async()=>setData(await api()),[]);
 useEffect(()=>{void refresh().catch(e=>setError(e.message));},[refresh]);
 async function run(f:()=>Promise<View|void>,msg:string){if(busy)return;setBusy(true);setError('');setNotice('');try{const v=await f();if(v)setData(v);setNotice(msg);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const toggle=(b:string)=>setBrands(x=>x.includes(b)?x.filter(y=>y!==b):[...x,b]);
 return <div className={s.root}><h1>팀 관리</h1><p className={s.warning}>로컬 Cora에 이미 가입한 계정만 초대할 수 있습니다. 초대 이메일은 발송하지 않으며, 초대받은 사람이 로그인해 이 화면에서 수락해야 권한이 생깁니다.</p>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
  <div className={s.grid}><section className={s.panel}><h2>팀원 초대</h2><p>편집자는 허용한 브랜드의 작업을 열고 저장할 수 있습니다. 검토자는 작업을 열 수 없고 검토 요청을 받을 사람으로만 표시됩니다. 검토 요청·삭제·게시 준비는 소유자만 할 수 있습니다.</p>
   <label>초대할 계정 이메일<input aria-label="초대할 계정 이메일" type="email" maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/></label>
   <label>역할<select aria-label="역할" value={role} onChange={e=>setRole(e.target.value as 'editor'|'reviewer')}><option value="editor">편집자</option><option value="reviewer">검토자</option></select></label>
   <fieldset style={{border:0,padding:0,margin:'8px 0'}}><legend>허용 브랜드(선택하지 않으면 전체 브랜드)</legend>{data?.brands.map(b=><label key={b} style={{display:'flex',flexDirection:'row',alignItems:'center',gap:8}}><input type="checkbox" style={{width:'auto',margin:0}} aria-label={`브랜드 ${b}`} checked={brands.includes(b)} onChange={()=>toggle(b)}/>{b}</label>)}{!data?.brands.length&&<p>저장한 브랜드 설정이 없어 전체 브랜드로 초대합니다.</p>}</fieldset>
   <button className={s.primary} disabled={busy||!email.trim()} onClick={()=>void run(()=>api({action:'invite',email,role,brands}),'초대를 저장했습니다. 상대가 수락하면 권한이 생깁니다.')}>팀원 초대</button></section>
  <section className={s.panel}><h2>내 워크스페이스 팀원</h2>{data?.members.map(m=><article className={s.row} key={m.id}><small>{roleLabel[m.role]} · {statusLabel[m.status]||m.status} · {brandText(m.brands)}</small><h3>{m.memberEmail}</h3><div className={s.actions}>{m.status!=='declined'&&<button disabled={busy} onClick={()=>void run(()=>api({action:'update',id:m.id,role:m.role==='editor'?'reviewer':'editor',brands:m.brands}),'역할을 바꿨습니다.')}>{m.role==='editor'?'검토자로 변경':'편집자로 변경'}</button>}{m.status!=='declined'&&<button disabled={busy} className={s.danger} onClick={()=>{if(window.confirm(`${m.memberEmail}의 팀 권한을 제거할까요? 바로 작업을 열 수 없게 됩니다.`))void run(()=>api({action:'remove',id:m.id}),'팀원을 제거했습니다.');}}>팀원 제거</button>}</div></article>)}{!data?.members.length&&<p>아직 초대한 팀원이 없습니다.</p>}</section></div>
  <div className={s.grid}><section className={s.panel}><h2>내가 받은 초대와 참여 중인 팀</h2>{data?.memberships.map(m=><article className={s.row} key={m.id}><small>{roleLabel[m.role]} · {statusLabel[m.status]} · {brandText(m.brands)}</small><h3>{m.ownerEmail}의 워크스페이스</h3><div className={s.actions}>{m.status==='invited'&&<><button disabled={busy} className={s.primary} onClick={()=>void run(()=>api({action:'accept',id:m.id}),'초대를 수락했습니다.')}>초대 수락</button><button disabled={busy} onClick={()=>void run(()=>api({action:'decline',id:m.id}),'초대를 거절했습니다.')}>초대 거절</button></>}{m.status==='active'&&<button disabled={busy} className={s.danger} onClick={()=>void run(()=>api({action:'remove',id:m.id}),'팀에서 나왔습니다.')}>팀에서 나가기</button>}</div></article>)}{!data?.memberships.length&&<p>받은 초대가 없습니다.</p>}</section>
  <section className={s.panel}><h2>편집할 수 있는 팀 작업</h2>{data?.sharedProjects.map(p=><article className={s.row} key={p.id}><small>{p.ownerEmail} · {p.brand} · v{p.version} · {new Date(p.updatedAt).toLocaleString('ko-KR')}</small><h3>{p.title}</h3><p>{p.count}장의 카드</p><button disabled={busy} onClick={()=>onOpen(p.id)}>팀 작업 열기</button></article>)}{!data?.sharedProjects.length&&<p>편집자로 참여 중인 작업이 없습니다.</p>}{!!data?.reviewerSuggestions.length&&<p>검토 요청을 보낼 수 있는 내 팀원: {data.reviewerSuggestions.join(', ')}</p>}</section></div></div>;
}
