'use client';
import {useState,useEffect,useCallback} from 'react';
import type {Member} from '@/lib/cora/team';
import s from './workbench.module.css';
type ClientLabel={id:string;name:string};
type Shared={id:string;brand:string;title:string;count:number;version:number;updatedAt:string;ownerEmail:string};
type View={members:Member[];memberships:Member[];sharedProjects:Shared[];reviewerSuggestions:string[];brands:string[];clients:ClientLabel[]};
const roleLabel={editor:'편집자',reviewer:'검토자'};
const statusLabel:Record<string,string>={invited:'수락 대기',active:'참여 중',declined:'거절함'};
async function api(data?:Record<string,unknown>):Promise<View>{const r=await fetch('/api/cora/team',{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json'}:undefined,body:data?JSON.stringify(data):undefined});const v=await r.json();if(!r.ok)throw new Error(v.error);return v;}
function scopeText(m:Member){return m.scope==='clients'?(m.clients.map(c=>`${c.name} (${c.id.slice(0,8)})`).join(', ')||'고객사 권한 없음'):(m.brands.join(', ')||'기존 이름 기준 전체 브랜드');}
function ClientChoices({clients,selected,onChange}:{clients:ClientLabel[];selected:string[];onChange:(ids:string[])=>void}){
 return <fieldset style={{border:0,padding:0,margin:'8px 0'}}><legend>허용 고객사 · 빈 선택은 권한 없음</legend>{clients.map(c=><label key={c.id} style={{display:'flex',flexDirection:'row',alignItems:'center',gap:8}}><input type="checkbox" style={{width:'auto',margin:0}} aria-label={`고객사 ${c.name} ${c.id.slice(0,8)}`} checked={selected.includes(c.id)} onChange={()=>onChange(selected.includes(c.id)?selected.filter(id=>id!==c.id):[...selected,c.id])}/>{c.name} · {c.id.slice(0,8)}</label>)}{!clients.length&&<p>먼저 고객사를 등록해 주세요.</p>}</fieldset>;
}
export function TeamDesk({onOpen,focused=true,onChanged}:{onOpen:(id:string)=>void;focused?:boolean;onChanged?:()=>void}){
 const[data,setData]=useState<View|null>(null),[email,setEmail]=useState(''),[role,setRole]=useState<'editor'|'reviewer'>('editor'),[brands,setBrands]=useState<string[]>([]),[clientIds,setClientIds]=useState<string[]>([]),[selections,setSelections]=useState<Record<string,string[]>>({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const refresh=useCallback(async()=>{setData(await api());setSelections({});onChanged?.();},[]);
 useEffect(()=>{void refresh().catch(e=>setError(e.message));},[refresh]);
 async function run(f:()=>Promise<View>,msg:string){if(busy)return;setBusy(true);setError('');setNotice('');try{setData(await f());setSelections({});setNotice(msg);onChanged?.();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const grant=(m:Member)=>focused?{clientIds:selections[m.id]??m.clientIds}:{brands:m.brands,...(m.scope==='clients'?{clientIds:m.clientIds}:{})};
 return <div className={s.root}><h1>팀 관리</h1><p className={s.warning}>Cora 가입 계정만 초대할 수 있습니다. 이메일은 발송하지 않습니다. 초대받은 사람이 이 화면에서 수락해야 권한이 생깁니다.</p>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<button disabled={busy} onClick={()=>void refresh().catch(e=>setError(e.message))}>팀 권한 새로고침</button>
 <div className={s.grid}><section className={s.panel}><h2>팀원 초대</h2><p>편집자는 선택한 고객사의 카드를 만들고 수정합니다. 검토자는 요청받은 저장 버전만 확인합니다. 고객사 설정·계정 연결·검토 요청·삭제·게시 준비는 소유자만 할 수 있습니다.</p><label>초대할 계정 이메일<input aria-label="초대할 계정 이메일" type="email" maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/></label><label>역할<select aria-label="역할" value={role} onChange={e=>setRole(e.target.value as 'editor'|'reviewer')}><option value="editor">편집자</option><option value="reviewer">검토자</option></select></label>
 {focused?<ClientChoices clients={data?.clients??[]} selected={clientIds} onChange={setClientIds}/>:<fieldset><legend>기존 허용 브랜드 · 빈 선택은 전체</legend>{data?.brands.map(b=><label key={b}><input type="checkbox" checked={brands.includes(b)} onChange={()=>setBrands(x=>x.includes(b)?x.filter(y=>y!==b):[...x,b])}/>{b}</label>)}</fieldset>}
 <button className={s.primary} disabled={busy||!email.trim()} onClick={()=>void run(()=>api({action:'invite',email,role,...(focused?{clientIds}:{brands})}),'초대를 저장했습니다. 상대가 수락하면 권한이 생깁니다.')}>팀원 초대</button></section>
 <section className={s.panel}><h2>내 워크스페이스 팀원</h2>{data?.members.map(m=><article className={s.row} key={m.id}><small>{roleLabel[m.role]} · {statusLabel[m.status]||m.status} · {scopeText(m)} · 권한 v{m.version}</small><h3>{m.memberEmail}</h3>{focused&&m.status!=='declined'&&<fieldset disabled={busy}><ClientChoices clients={data.clients} selected={selections[m.id]??m.clientIds} onChange={ids=>setSelections({...selections,[m.id]:ids})}/></fieldset>}<div className={s.actions}>{m.status!=='declined'&&<><button disabled={busy} onClick={()=>void run(()=>api({action:'update',id:m.id,version:m.version,role:m.role,...grant(m)}),'고객사 권한을 저장했습니다. 빈 목록이면 접근을 회수합니다.')}>권한 저장</button><button disabled={busy} onClick={()=>void run(()=>api({action:'update',id:m.id,version:m.version,role:m.role==='editor'?'reviewer':'editor',...grant(m)}),'역할을 바꿨습니다.')}>{m.role==='editor'?'검토자로 변경':'편집자로 변경'}</button></>}<button disabled={busy} className={s.danger} onClick={()=>{if(window.confirm(`${m.memberEmail}의 팀 권한을 제거할까요?`))void run(()=>api({action:'remove',id:m.id,version:m.version}),'팀원을 제거했습니다.');}}>팀원 제거</button></div></article>)}{!data?.members.length&&<p>아직 초대한 팀원이 없습니다.</p>}</section></div>
 <div className={s.grid}><section className={s.panel}><h2>내가 받은 초대와 참여 중인 팀</h2>{data?.memberships.map(m=><article className={s.row} key={m.id}><small>{roleLabel[m.role]} · {statusLabel[m.status]} · {scopeText(m)}</small><h3>{m.ownerEmail}의 워크스페이스</h3><div className={s.actions}>{m.status==='invited'&&<><button disabled={busy} className={s.primary} onClick={()=>void run(()=>api({action:'accept',id:m.id,version:m.version}),'초대를 수락했습니다.')}>초대 수락</button><button disabled={busy} onClick={()=>void run(()=>api({action:'decline',id:m.id,version:m.version}),'초대를 거절했습니다.')}>초대 거절</button></>}{m.status==='active'&&<button disabled={busy} className={s.danger} onClick={()=>void run(()=>api({action:'remove',id:m.id,version:m.version}),'팀에서 나왔습니다.')}>팀에서 나가기</button>}</div></article>)}{!data?.memberships.length&&<p>받은 초대가 없습니다.</p>}</section>
 <section className={s.panel}><h2>편집할 수 있는 팀 작업</h2>{data?.sharedProjects.map(p=><article className={s.row} key={p.id}><small>{p.ownerEmail} · {p.brand} · v{p.version}</small><h3>{p.title}</h3><p>{p.count}장의 카드</p><button disabled={busy} onClick={()=>onOpen(p.id)}>팀 작업 열기</button></article>)}{!data?.sharedProjects.length&&<p>편집자로 참여 중인 작업이 없습니다.</p>}</section></div></div>;
}
