'use client';
import {useEffect,useRef,useState} from 'react';
import {monday,shiftDay,validDay,freshnessLabel,type WeeklySource,type MaterialCandidate,type PresentedPlan,type WeekPlan,type WeekSlot} from '@/lib/cora/weekly-model';
import s from './workbench.module.css';
type Form={id?:string;version?:number;weekStart:string;goal:string;pool:string[];selected:WeekSlot[]};
type State={client:{name:string;goal:string;version:number};sources:WeeklySource[];candidates:MaterialCandidate[];plans:{id:string;version:number;weekStart:string;goal:string}[];current:PresentedPlan|null;actors:{id:string;email:string}[];history:{version:number;createdAt:string;plan:WeekPlan}[];materialItems:{id:string;title:string}[]};
const empty=():Form=>({weekStart:monday(),goal:'이번 주 고객사 콘텐츠 준비',pool:[],selected:[]});
const formOf=(p:WeekPlan):Form=>({id:p.id,version:p.version,weekStart:p.weekStart,goal:p.goal,pool:p.pool,selected:p.selected});
export function WeeklyDesk({clientId,onOpenProject,onDirtyChange}:{clientId:string;onOpenProject:(id:string)=>void;onDirtyChange:(dirty:boolean)=>void}){
 const alive=useRef(false),[data,setData]=useState<State|null>(null),[form,setForm]=useState<Form>(empty),[baseline,setBaseline]=useState(''),[sourceIds,setSourceIds]=useState<string[]>([]),[display,setDisplay]=useState<MaterialCandidate[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [sourceTitle,setSourceTitle]=useState(''),[sourceText,setSourceText]=useState(''),[sourceURL,setSourceURL]=useState(''),[publishedOn,setPublishedOn]=useState(''),[copyWeek,setCopyWeek]=useState(shiftDay(monday(),7));
 const planDirty=!!baseline&&JSON.stringify(form)!==baseline,dirty=planDirty||!!(sourceTitle||sourceText||sourceURL||publishedOn);
 async function request(input?:Record<string,unknown>,planId?:string){const r=await fetch('/api/cora/weekly?'+new URLSearchParams({clientId,...(planId?{planId}:{})}),{method:input?'POST':'GET',headers:input?{'Content-Type':'application/json'}:undefined,body:input?JSON.stringify({...input,clientId}):undefined});const v=await r.json();if(!r.ok)throw new Error(v.error||'주간 제작 요청 실패');return v;}
 async function load(planId?:string,preserve=false){const v=await request(undefined,planId) as State;if(!alive.current)return;setData(v);if(!preserve){const f=v.current?formOf(v.current):{...empty(),goal:v.client.goal||empty().goal,pool:v.candidates.map(x=>x.id)};setForm(f);setBaseline(JSON.stringify(f));setDisplay(v.current?.candidates??v.candidates);setCopyWeek(shiftDay(f.weekStart,7));}}
 useEffect(()=>{alive.current=true;if(clientId)void load().catch(e=>{if(alive.current)setError(e.message);});return()=>{alive.current=false;onDirtyChange(false);};},[clientId]);
 useEffect(()=>{onDirtyChange(dirty);const before=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',before);return()=>window.removeEventListener('beforeunload',before);},[dirty,onDirtyChange]);
 async function run(f:()=>Promise<void>){if(busy)return;setBusy(true);setError('');setNotice('');try{await f();}catch(e){if(alive.current)setError((e as Error).message);}finally{if(alive.current)setBusy(false);}}
 function choose(id:string,checked:boolean){setForm(f=>({...f,selected:checked?[...f.selected,{candidateId:id,reason:'',assigneeId:'',deadline:'',projectId:null}]:f.selected.filter(x=>x.candidateId!==id)}));}
 function patch(id:string,value:Partial<WeekSlot>){setForm(f=>({...f,selected:f.selected.map(x=>x.candidateId===id?{...x,...value}:x)}));}
 const resetSource=()=>{setSourceTitle('');setSourceText('');setSourceURL('');setPublishedOn('');};
 const addSource=async(input:Record<string,unknown>)=>{const r=await request({action:'source',...input});await load(form.id,true);if(!alive.current)return;resetSource();setSourceIds(ids=>[r.source.id,...ids].slice(0,5));setNotice('근거 자료를 저장했습니다. 게시일과 원문을 확인한 뒤 후보를 만드세요.');};
 if(!clientId)return <div className={s.root}><h1>이번 주 콘텐츠 묶음</h1><p>먼저 작업 고객사를 선택하세요. 자료·후보·계획은 고객사별로 보관합니다.</p></div>;
 if(!data)return <div className={s.root}><h1>이번 주 콘텐츠 묶음</h1>{error?<><p role="alert">{error}</p><button onClick={()=>void run(()=>load())}>자료 다시 불러오기</button></>:<p role="status">고객사 자료와 저장한 계획을 불러옵니다.</p>}</div>;
 return <div className={s.root}><h1>이번 주 콘텐츠 묶음</h1><p>{data?.client.name} · 근거 자료 → 후보5개 → 이번 주3개 → 담당·마감 → 카드 편집</p><p>자료 기반 편집 방향입니다. 실시간 트렌드 발굴·AI 생성·자동 게시가 아닙니다. 같은 원문의 다른 구성을 비교하고 사실을 직접 확인하세요.</p>
 {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{dirty&&<p role="status">주간 화면에 저장하지 않은 입력이 있습니다. 이 화면은 자동 복구함에 저장되지 않으므로 자료·계획을 저장하세요.</p>}
 <fieldset className={s.content} disabled={busy}><section className={s.panel}><h2>1. 근거 자료 모으기</h2><label>자료 이름<input aria-label="주간 자료 이름" maxLength={200} value={sourceTitle} onChange={e=>setSourceTitle(e.target.value)}/></label><label>원문 직접 입력<textarea aria-label="주간 원문 자료" rows={5} maxLength={20000} value={sourceText} onChange={e=>setSourceText(e.target.value)}/></label><label>출처 URL (선택) / 공개 글 가져오기<input aria-label="주간 출처 URL" type="url" maxLength={1500} value={sourceURL} onChange={e=>setSourceURL(e.target.value)} placeholder="https://…"/></label><label>게시일 (사용자가 확인한 날짜, 선택)<input aria-label="주간 자료 게시일" type="date" value={publishedOn} onChange={e=>setPublishedOn(e.target.value)}/></label>
 <button disabled={sourceText.trim().length<10} onClick={()=>void run(()=>addSource({source:{title:sourceTitle,text:sourceText,url:sourceURL,publishedOn}}))}>직접 자료 저장</button><button disabled={!sourceURL||!!sourceText.trim()} onClick={()=>void run(()=>addSource({url:sourceURL,publishedOn}))}>공개 URL 본문 가져오기</button><p>URL 읽기 실패 시 창작으로 채우지 않습니다. 직접 입력한 글과 URL 본문은 실행 없이 참고 자료로만 다룹니다. 가져온 본문은 최대16,000자이며 잘림을 표시합니다.</p>
 {!!data?.materialItems.length&&<label>이 고객사에 저장한 소재 가져오기<select aria-label="저장 소재를 주간 자료로" value="" onChange={e=>{if(e.target.value)void run(()=>addSource({materialId:e.target.value}));}}><option value="">선택 후 새 근거 자료로 복사</option>{data.materialItems.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label>}
 {data?.sources.map(src=><article key={src.id} className={s.row}><label><input type="checkbox" aria-label={'후보 근거 선택 '+src.title} checked={sourceIds.includes(src.id)} disabled={!sourceIds.includes(src.id)&&sourceIds.length>=5} onChange={e=>setSourceIds(ids=>e.target.checked?[...ids,src.id]:ids.filter(id=>id!==src.id))}/>{src.title}</label><p>출처: {src.url?<a href={src.url} target="_blank" rel="noreferrer">{src.url}</a>:'링크 없음 · 직접 제공한 자료'} · 수집 {src.collectedAt} · 게시일 {src.publishedOn||'미확인'}{src.truncated?' · 본문 일부만 추출됨':''}{src.duplicateIds.length?' · 기존 자료와 원문/주소 중복':''}</p><details><summary>보관 원문 보기</summary><p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{src.text}</p></details></article>)}
 <button disabled={!sourceIds.length} onClick={()=>{if(form.selected.length&&!window.confirm('새 후보로 계획 입력을 교체할까요? 이미 만든 작업물과 이전 계획 이력은 보존됩니다.'))return;void run(async()=>{const r=await request({action:'candidates',sourceIds});await load(form.id,true);if(!alive.current)return;setDisplay(r.candidates);setForm(f=>({...f,pool:r.candidates.map((c:MaterialCandidate)=>c.id),selected:[]}));setNotice('자료 기반 후보5개를 만들었습니다. 이번 주3개를 고르고 계획을 저장하세요.');});}}>자료로 후보5개 만들기</button></section>
 <section className={s.panel}><h2>2. 이번 주3개 선택·담당·마감</h2>{!!data?.plans.length&&<label>저장한 주간 계획<select aria-label="주간 계획 선택" value={form.id??''} onChange={e=>{if(planDirty&&!window.confirm('저장하지 않은 계획 변경을 두고 다른 계획을 열까요?'))return;void run(()=>load(e.target.value||undefined));}}>{!form.id&&<option value="">새 계획</option>}{data.plans.map(p=><option key={p.id} value={p.id}>{p.weekStart} · {p.goal} · v{p.version}</option>)}</select></label>}
 <label>주 시작일 (월요일)<input aria-label="주간 계획 시작일" type="date" value={form.weekStart} onChange={e=>setForm({...form,weekStart:e.target.value})}/></label><label>이번 주 목표<input aria-label="주간 제작 목표" maxLength={200} value={form.goal} onChange={e=>setForm({...form,goal:e.target.value})}/></label>
 <p>{form.selected.length}/3개 선택 · 규칙 버전은 후보 생성 당시 값이며 카드 초안은 생성 시 최신 규칙을 참조합니다.</p>
 {display.map(c=>{const slot=form.selected.find(x=>x.candidateId===c.id);return <article key={c.id} className={s.row}><h3>{c.title}</h3><label><input type="checkbox" aria-label={'이번 주 후보 선택 '+c.angle} checked={!!slot} disabled={!slot&&form.selected.length>=3} onChange={e=>choose(c.id,e.target.checked)}/>이번 주 제작</label><p>{c.fitReason}</p><p>{freshnessLabel(c.freshness)} (후보 생성 당시, 게시일은 사용자 입력) · 수집 {c.collectedAt} · 브랜드 규칙 v{c.brandVersion}{c.brandVersion!==data?.client.version?' · 현재 규칙과 다름, 확인 필요':''}</p><p>출처: {c.sourceUrl?<a href={c.sourceUrl} target="_blank" rel="noreferrer">{c.sourceTitle}</a>:'링크 없음 · 직접 제공 자료'}{c.sameSourceInBatch?' · 같은 원문의 다른 구성, 내용 겹침 확인':''}{c.duplicateIds.length?' · 이전 후보에도 같은 원문/주소 있음':''}{c.excerptOnly?' · 원문 일부 발췌':''}</p><details><summary>후보의 근거 발췌</summary><p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{c.excerpt}</p></details>{slot&&<><label>선택 이유<textarea aria-label={'후보 선택 이유 '+c.angle} rows={2} maxLength={500} value={slot.reason} onChange={e=>patch(c.id,{reason:e.target.value})}/></label><label>담당자<select aria-label={'후보 담당자 '+c.angle} value={slot.assigneeId} onChange={e=>patch(c.id,{assigneeId:e.target.value})}><option value="">현재 편집 권한이 있는 담당자 선택</option>{slot.assigneeId&&!data?.actors.some(a=>a.id===slot.assigneeId)&&<option value={slot.assigneeId}>권한 변경됨 · 다시 선택</option>}{data?.actors.map(a=><option key={a.id} value={a.id}>{a.email}</option>)}</select></label><label>초안 마감일<input aria-label={'후보 마감일 '+c.angle} type="date" min={form.weekStart} max={validDay(form.weekStart)?shiftDay(form.weekStart,6):undefined} value={slot.deadline} onChange={e=>patch(c.id,{deadline:e.target.value})}/></label></> }</article>;})}
 <button className={s.primary} disabled={form.pool.length!==5||!form.goal.trim()} onClick={()=>void run(async()=>{const r=await request({action:'plan',plan:form});await load(r.plan.id);if(alive.current)setNotice('주간 계획을 저장했습니다.3개 후보의 이유·담당·마감이 모두 있어야 카드 초안을 만듭니다.');})}>주간 계획 저장</button>
 {form.id&&<button onClick={()=>{if(planDirty&&!window.confirm('저장하지 않은 계획 변경을 버리고 최신 저장본을 불러올까요?'))return;void run(()=>load(form.id));}}>최신 계획 다시 불러오기</button>}</section>
 {data?.current&&<section className={s.panel}><h2>3. 저장된 계획에서 카드 제작</h2><p>계획 v{data.current.version} · {data.current.prepared?'제작 준비됨':'선택 이유·담당·마감 확인 필요'} · 게시 일정이나 고객 승인을 뜻하지 않습니다.</p>{data.current.overlapWarnings.map((w,i)=><p key={i}>{w}</p>)}{data.current.slots.map(slot=>{const c=data.current!.candidates.find(x=>x.id===slot.candidateId);return <article key={slot.candidateId} className={s.row}><h3>{c?.title}</h3><p>마감 {slot.deadline||'미지정'} · {slot.assigneeAvailable?'담당 권한 있음':'담당자 권한 확인 필요'}</p>{slot.project?<><p>연결된 카드 v{slot.project.version} · {slot.project.workStatus==='ready'?'내 검토 완료':slot.project.workStatus==='review'?'검토 필요':'작성 중'}</p><button onClick={()=>onOpenProject(slot.project!.id)}>연결된 카드 편집</button></>:<><p>{slot.missingProject?'연결했던 작업이 삭제되거나 다른 고객사로 옮겨졌습니다. 새 초안을 만들 수 있습니다.':'아직 제작물 없음'}</p><button disabled={planDirty||!data.current!.prepared} onClick={()=>void run(async()=>{const r=await request({action:'draft',id:data.current!.id,version:data.current!.version,candidateId:slot.candidateId});await load(r.plan.id);if(alive.current)onOpenProject(r.projectId);})}>카드 초안 만들고 편집</button></>}</article>;})}
 <label>복제할 주 시작일<input aria-label="다음 주 복제 시작일" type="date" value={copyWeek} onChange={e=>setCopyWeek(e.target.value)}/></label><button disabled={planDirty} onClick={()=>void run(async()=>{const r=await request({action:'duplicate',id:data.current!.id,version:data.current!.version,weekStart:copyWeek});await load(r.plan.id);if(alive.current)setNotice('다른 주 계획으로 복제했습니다. 작업물 연결과 승인은 복제하지 않았고 AI를 호출하지 않았습니다.');})}>다른 주 계획으로 복제</button>
 <details><summary>주간 계획 수정 이력</summary>{data.history.map(h=><article key={h.version}><p>v{h.version} · {h.createdAt} · {h.plan.weekStart} · {h.plan.goal}</p><ul>{h.plan.selected.map(slot=><li key={slot.candidateId}>{slot.reason||'이유 미입력'} · {slot.deadline||'마감 미정'} · {slot.projectId?'당시 카드 연결 있음':'당시 카드 없음'}</li>)}</ul></article>)}</details></section>}
 </fieldset></div>;
}
