'use client';

import { useEffect, useState } from 'react';
import s from './workbench.module.css';

type Item = { id: string; kind: string; title: string; data: Record<string, unknown>; createdAt: string };
type Article = { title: string; url: string; summary: string; sourceName: string; publishedAt: string };
type Tab = 'material' | 'writing' | 'analysis' | 'calendar' | 'automation' | 'library';
const tabs: [Tab, string][] = [['material','소재 탐색'],['writing','AI 글·대본'],['analysis','성과 분석'],['calendar','콘텐츠 달력'],['automation','자동화 레시피'],['library','자산 보관함']];
const names: Record<string,string> = {video:'MP4 영상',material:'소재',blog:'블로그',script:'영상 대본',ideas:'아이디어',analysis:'성과 분석',calendar:'발행 계획',automation:'자동화 레시피'};
const str = (v: unknown) => typeof v === 'string' ? v : '';
function download(text: string, name: string) { const url = URL.createObjectURL(new Blob([text], {type:'text/plain;charset=utf-8'})); const a = document.createElement('a'); a.href=url; a.download=name; a.click(); setTimeout(()=>URL.revokeObjectURL(url),1000); }

export function Workbench({onBack,onUseMaterial}: {onBack:()=>void;onUseMaterial:(text:string,url:string)=>void}) {
 const [tab,setTab]=useState<Tab>('material'); const [items,setItems]=useState<Item[]>([]); const [llm,setLlm]=useState(false);
 const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [notice,setNotice]=useState('');
 const [query,setQuery]=useState(''); const [articles,setArticles]=useState<Article[]>([]); const [url,setUrl]=useState(''); const [material,setMaterial]=useState(''); const [materialTitle,setMaterialTitle]=useState('');
 const [brand,setBrand]=useState(''); const [format,setFormat]=useState('blog'); const [instructions,setInstructions]=useState(''); const [selected,setSelected]=useState<Item|null>(null); const [editText,setEditText]=useState('');
 const [csv,setCsv]=useState(''); const [analysis,setAnalysis]=useState<Item|null>(null);
 const [planTitle,setPlanTitle]=useState('');const [scheduledAt,setScheduledAt]=useState('');const [platform,setPlatform]=useState('Instagram');const [account,setAccount]=useState('');const [caption,setCaption]=useState('');
 const [recipeTitle,setRecipeTitle]=useState(''); const [prompt,setPrompt]=useState(''); const [frequency,setFrequency]=useState('주 1회'); const [filter,setFilter]=useState('all');
 async function api(body?:Record<string,unknown>) { const res=await fetch('/api/cora/workbench',{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined}); const value=await res.json(); if(!res.ok)throw new Error(value.error||'요청을 처리하지 못했습니다.'); return value; }
 async function refresh(){const data=await api();setItems(data.items||[]);setLlm(Boolean(data.capabilities?.llm));}
 async function run(fn:()=>Promise<void>){if(busy)return;setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'작업 중 오류가 발생했습니다.');}finally{setBusy(false);}}
 useEffect(()=>{let active=true;api().then(data=>{if(active){setItems(data.items||[]);setLlm(Boolean(data.capabilities?.llm));}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
 async function save(kind:string,title:string,data:Record<string,unknown>){if(!title.trim())throw new Error('제목을 입력해 주세요.');await api({action:'save',kind,title,data});await refresh();setNotice('내 보관함에 저장했습니다.');}
 function open(item:Item){setSelected(item);setEditText(str(item.data.text));if(item.kind==='material'&&item.data.format==='ideas'){setFormat('ideas');setTab('writing');}else if(item.kind==='analysis'){setAnalysis(item);setTab('analysis');}else if(item.kind==='material'){setMaterial(str(item.data.text)||str(item.data.summary));setMaterialTitle(item.title);setUrl(str(item.data.url));setTab('material');}else if(['blog','script','ideas'].includes(item.kind)){setFormat(item.kind);setTab('writing');}else if(item.kind==='calendar'){setPlanTitle(item.title);setScheduledAt(str(item.data.scheduledAt));setPlatform(str(item.data.platform));setAccount(str(item.data.accountLabel));setCaption(str(item.data.caption));setTab('calendar');}else if(item.kind==='automation'){setRecipeTitle(item.title);setPrompt(str(item.data.prompt));setFrequency(str(item.data.frequency));setBrand(str(item.data.brand));setTab('automation');}}
 async function generate(custom?:string){if(!material.trim())throw new Error('생성에 사용할 소재를 입력해 주세요.');const data=await api({action:'generate',format,material,brand,instructions:custom??instructions});setSelected(data.item);setEditText(str(data.item.data.text));setTab('writing');await refresh();setNotice('생성 결과를 보관함에 저장했습니다. 내용을 검토한 뒤 사용해 주세요.');}
 const analysisData=analysis?.data; const rows=Array.isArray(analysisData?.rows)?analysisData.rows:[];
 return <div className={s.root}>
  <header className={s.header}><div><span className={s.eyebrow}>CORA / CONTENT OPERATIONS</span><h1>콘텐츠 작업실</h1><p>소재에서 제작, 발행 계획과 성과 개선까지 한 곳에서 이어갑니다.</p></div><button onClick={onBack}>카드뉴스 제작실로</button></header>
  <nav className={s.tabs} aria-label="콘텐츠 작업 메뉴">{tabs.map(([id,label])=><button key={id} className={tab===id?s.active:''} aria-current={tab===id?'page':undefined} onClick={()=>setTab(id)}>{label}</button>)}</nav>
  {busy&&<p role="status" className={s.notice}>작업 중입니다. 잠시 기다려 주세요.</p>}{error&&<p role="alert" className={s.error}>{error}</p>}{notice&&<p role="status" className={s.notice}>{notice}</p>}
  <fieldset disabled={busy} className={s.content}>
   {tab==='material'&&<><div className={s.grid}><section className={s.panel}><span className={s.eyebrow}>DISCOVER</span><h2>지금 다룰 소재 찾기</h2><p>RSS 뉴스에서 후보를 찾아 원문과 출처를 확인합니다. 검색 결과 요약은 원문 전체가 아닙니다.</p><label>소재 검색어<input aria-label="소재 검색어" value={query} onChange={e=>setQuery(e.target.value)} placeholder="예: 독립서점, 지속가능한 패션"/></label><button className={s.primary} onClick={()=>run(async()=>{if(!query.trim())throw new Error('검색어를 입력해 주세요.');const data=await api({action:'discover',query});setArticles(data.articles||[]);setNotice(`${(data.articles||[]).length}개 소재를 찾았습니다.${data.failed?.length?' 일부 출처를 불러오지 못했습니다.':''}`);})}>소재 검색</button></section>
   <section className={s.panel}><span className={s.eyebrow}>IMPORT</span><h2>링크·자료로 시작</h2><label>원문 URL<input aria-label="원문 URL" type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://…"/></label><button onClick={()=>run(async()=>{const data=await api({action:'fetch',url});setMaterial(data.text);setMaterialTitle(data.title);setUrl(data.url||url);setNotice('원문을 가져왔습니다. 추출 내용을 확인해 주세요.');})}>링크 본문 가져오기</button><p className={s.muted}>로그인·유료·동적 페이지는 본문 추출이 제한될 수 있습니다. 직접 자료를 붙여 넣어도 됩니다.</p></section></div>
   {articles.length>0&&<div className={s.cards}>{articles.map((a,i)=><article className={s.panel} key={`${a.url}-${i}`}><small>{a.sourceName} · {a.publishedAt?new Date(a.publishedAt).toLocaleDateString('ko-KR'):''}</small><h3>{a.title}</h3><p>{a.summary}</p><div className={s.actions}><a href={a.url} target="_blank" rel="noreferrer">출처 열기 ↗</a><button onClick={()=>{setMaterial(a.summary);setUrl(a.url);setMaterialTitle(a.title);setNotice('RSS 요약을 선택했습니다. 더 자세한 내용은 링크 본문 가져오기로 확인하세요.');}}>요약 선택</button></div></article>)}</div>}
   <section className={s.panel}><h2>선택한 소재</h2><label>소재 제목<input aria-label="소재 제목" value={materialTitle} onChange={e=>setMaterialTitle(e.target.value)}/></label><label>소재 본문<textarea aria-label="소재 본문" rows={9} value={material} onChange={e=>setMaterial(e.target.value)} placeholder="브랜드 자료나 확인한 원문 내용을 붙여 넣으세요."/></label><div className={s.actions}><button disabled={!material.trim()} onClick={()=>run(()=>save('material',materialTitle||'제목 없는 소재',{text:material,url}))}>소재 저장</button><button disabled={!material.trim()} onClick={()=>setTab('writing')}>AI 글·대본으로 이어가기</button><button className={s.primary} disabled={!material.trim()} onClick={()=>onUseMaterial(material,url)}>카드뉴스로 만들기</button></div></section></>}
   {tab==='writing'&&<div className={s.grid}><section className={s.panel}><span className={s.eyebrow}>WRITE</span><h2>소재를 콘텐츠로</h2><p className={llm?s.notice:s.muted}>{llm?'AI 생성 경로가 준비되어 있습니다. 제공자 연결 여부는 실제 생성 응답으로 확인합니다.':'AI 연결 전입니다. 서버의 모델 설정 후 생성할 수 있습니다. 직접 작성한 글도 저장할 수 있습니다.'}</p><label>브랜드·독자<input aria-label="브랜드·독자" value={brand} onChange={e=>setBrand(e.target.value)} placeholder="누구에게 어떤 목소리로 말할까요?"/></label><label>만들 형식<select aria-label="만들 형식" value={format} onChange={e=>setFormat(e.target.value)}><option value="blog">블로그 글</option><option value="script">숏폼 영상 대본</option><option value="ideas">콘텐츠 아이디어</option></select></label><label>생성용 소재<textarea aria-label="생성용 소재" rows={7} value={material} onChange={e=>setMaterial(e.target.value)}/></label><label>추가 지시<textarea aria-label="추가 지시" rows={3} value={instructions} onChange={e=>setInstructions(e.target.value)} placeholder="분량, 말투, 금지 표현, 행동 유도 문구 등"/></label><button className={s.primary} disabled={!llm||!material.trim()} onClick={()=>run(()=>generate())}>AI 콘텐츠 생성</button></section><section className={s.panel}><h2>{selected&&['blog','script','ideas'].includes(selected.kind)?selected.title:'결과 편집'}</h2><p className={s.muted}>{selected?.data.provider?`생성: ${str(selected.data.provider)} · ${str(selected.data.model)}`:'직접 작성하거나 생성한 결과를 편집하세요.'}</p><label>콘텐츠 본문<textarea aria-label="콘텐츠 본문" rows={20} value={editText} onChange={e=>setEditText(e.target.value)}/></label><div className={s.actions}><button disabled={!editText.trim()} onClick={()=>run(()=>save(format==='script'?'script':format==='ideas'?'material':'blog',selected?.title||`${brand||'새'} 콘텐츠`,{text:editText,format,source:material,provider:selected?.data.provider||'manual',model:selected?.data.model||''}))}>편집본 새로 저장</button><button disabled={!editText.trim()} onClick={()=>run(async()=>{await navigator.clipboard.writeText(editText);setNotice('본문을 복사했습니다.');})}>본문 복사</button><button disabled={!editText.trim()} onClick={()=>download(editText,format==='script'?'cora-script.txt':'cora-content.md')}>파일 다운로드</button>{typeof selected?.data.srt==='string'&&<button onClick={()=>download(str(selected.data.srt),'cora-captions.srt')}>SRT 다운로드</button>}</div></section></div>}
   {tab==='analysis'&&<><section className={s.panel}><span className={s.eyebrow}>LEARN</span><h2>내 게시물 성과에서 다음 실험 찾기</h2><p>CSV를 직접 가져와 실제 기록을 분석합니다. 필수 열: date,title,reach,saves,likes,comments (최대 500행). Instagram 계정 실시간 연결이나 인과 효과 추정은 아닙니다.</p><label>성과 CSV 파일<input aria-label="성과 CSV 파일" type="file" accept=".csv,text/csv" onChange={e=>{const f=e.target.files?.[0];if(f)void run(async()=>{if(f.size>2_000_000)throw new Error('2MB 이하 CSV를 사용해 주세요.');setCsv(await f.text());});}}/></label><label>CSV 데이터<textarea aria-label="CSV 데이터" rows={7} value={csv} onChange={e=>setCsv(e.target.value)} placeholder={'date,title,reach,saves,likes,comments\n2026-09-29,게시물 제목,1000,12,40,3'}/></label><button className={s.primary} disabled={!csv.trim()} onClick={()=>run(async()=>{const data=await api({action:'analyze',csv});setAnalysis(data.item);await refresh();setNotice('분석 결과를 저장했습니다.');})}>CSV 성과 분석</button></section>
   {analysisData&&<section className={s.panel}><h2>{analysis?.title}</h2><p className={s.pre}>{str(analysisData.summary)}</p>{Array.isArray(analysisData.warnings)&&analysisData.warnings.map((v,i)=><p className={s.warning} key={i}>{String(v)}</p>)}<h3>다음 콘텐츠에 적용할 제안</h3><ul>{Array.isArray(analysisData.recommendations)&&analysisData.recommendations.map((v,i)=><li key={i}>{String(v)}</li>)}</ul>{rows.length>0&&<div className={s.tableWrap}><table><thead><tr>{Object.keys(rows[0]).map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{rows.slice(0,100).map((row,i)=><tr key={i}>{Object.keys(rows[0]).map(k=><td key={k}>{typeof row[k]==='object'?JSON.stringify(row[k]):String(row[k]??'')}</td>)}</tr>)}</tbody></table></div>}<button onClick={()=>download(JSON.stringify(analysisData,null,2),'cora-analysis.json')}>분석 결과 다운로드</button></section>}</>}
   {tab==='calendar'&&<div className={s.grid}><section className={s.panel}><span className={s.eyebrow}>PLAN</span><h2>발행 계획 등록</h2><p className={s.warning}>이 달력은 내부 제작·발행 계획입니다. 저장만으로 SNS에 예약 게시되지 않습니다.</p><label>발행 계획 제목<input aria-label="발행 계획 제목" value={planTitle} onChange={e=>setPlanTitle(e.target.value)}/></label><label>예정 일시 (현재 기기 시간대)<input aria-label="예정 일시 (현재 기기 시간대)" type="datetime-local" value={scheduledAt} onChange={e=>setScheduledAt(e.target.value)}/></label><label>플랫폼<select aria-label="플랫폼" value={platform} onChange={e=>setPlatform(e.target.value)}>{['Instagram','YouTube','TikTok','LinkedIn','블로그'].map(p=><option key={p}>{p}</option>)}</select></label><label>계정·브랜드 이름<input aria-label="계정·브랜드 이름" value={account} onChange={e=>setAccount(e.target.value)}/></label><label>게시 문구<textarea aria-label="게시 문구" rows={5} value={caption} onChange={e=>setCaption(e.target.value)}/></label><button className={s.primary} onClick={()=>run(async()=>{if(!scheduledAt)throw new Error('예정 일시를 입력해 주세요.');await save('calendar',planTitle,{scheduledAt,platform,caption,accountLabel:account,status:'planned'});})}>발행 계획 저장</button></section><section className={s.panel}><h2>예정된 콘텐츠</h2>{items.filter(i=>i.kind==='calendar').sort((a,b)=>str(a.data.scheduledAt).localeCompare(str(b.data.scheduledAt))).map(item=><article className={s.row} key={item.id}><small>{str(item.data.scheduledAt).replace('T',' ')} · {str(item.data.platform)} · 내부 계획</small><h3>{item.title}</h3><p>{str(item.data.accountLabel)}</p><p className={s.pre}>{str(item.data.caption)}</p><button onClick={()=>open(item)}>불러와 새 계획 작성</button></article>)}{!items.some(i=>i.kind==='calendar')&&<p>아직 등록한 발행 계획이 없습니다.</p>}</section></div>}
   {tab==='automation'&&<div className={s.grid}><section className={s.panel}><span className={s.eyebrow}>REPEAT</span><h2>반복 작업 레시피</h2><p>자주 쓰는 생성 지시를 보관하고 현재 소재로 실행합니다. 주기는 운영 메모이며 백그라운드 자동 실행은 아직 연결 전입니다.</p><label>레시피 제목<input aria-label="레시피 제목" value={recipeTitle} onChange={e=>setRecipeTitle(e.target.value)}/></label><label>레시피 브랜드<input aria-label="레시피 브랜드" value={brand} onChange={e=>setBrand(e.target.value)}/></label><label>운영 주기 메모<input aria-label="운영 주기 메모" value={frequency} onChange={e=>setFrequency(e.target.value)}/></label><label>반복할 지시<textarea aria-label="반복할 지시" rows={8} value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="매주 브랜드 소식으로 30초 숏폼 대본을 작성해 주세요…"/></label><button className={s.primary} onClick={()=>run(async()=>{if(!prompt.trim())throw new Error('반복할 지시를 입력해 주세요.');await save('automation',recipeTitle,{prompt,frequency,brand});})}>레시피 저장</button></section><section className={s.panel}><h2>저장한 레시피</h2><label>이번 실행에 사용할 소재<textarea aria-label="이번 실행에 사용할 소재" rows={5} value={material} onChange={e=>setMaterial(e.target.value)}/></label><label>실행 결과 형식<select aria-label="실행 결과 형식" value={format} onChange={e=>setFormat(e.target.value)}><option value="blog">블로그</option><option value="script">숏폼 대본</option><option value="ideas">아이디어</option></select></label>{items.filter(i=>i.kind==='automation').map(item=><article className={s.row} key={item.id}><small>{str(item.data.frequency)}</small><h3>{item.title}</h3><p className={s.pre}>{str(item.data.prompt)}</p><div className={s.actions}><button onClick={()=>open(item)}>불러오기</button><button disabled={!llm||!material.trim()} onClick={()=>run(async()=>{const data=await api({action:'generate',format,material,brand:str(item.data.brand),instructions:str(item.data.prompt)});setSelected(data.item);setEditText(str(data.item.data.text));setTab('writing');await refresh();setNotice('레시피 실행 결과를 저장했습니다.');})}>이 소재로 지금 실행</button></div></article>)}{!items.some(i=>i.kind==='automation')&&<p>아직 저장한 레시피가 없습니다.</p>}</section></div>}
   {tab==='library'&&<section className={s.panel}><div className={s.libraryHead}><div><span className={s.eyebrow}>YOUR ASSETS</span><h2>내 콘텐츠 자산</h2></div><label>자산 종류<select aria-label="자산 종류" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">전체</option>{Object.entries(names).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label></div>{items.filter(item=>filter==='all'||item.kind===filter).map(item=><article className={s.row} key={item.id}><small>{names[item.kind]||item.kind} · {new Date(item.createdAt).toLocaleString('ko-KR')}</small><h3>{item.title}</h3><p>{(str(item.data.text)||str(item.data.summary)||str(item.data.caption)||str(item.data.prompt)).slice(0,180)}</p><div className={s.actions}>{item.kind==='video'?(item.data.status==='ready'?<a href={`/api/cora/video/${item.id}`} download>MP4 다운로드</a>:<span>{item.data.status==='failed'?'렌더 실패':'렌더 진행 중'}</span>):<button onClick={()=>open(item)}>열기</button>}<button onClick={()=>download(JSON.stringify(item,null,2),'cora-asset.json')}>JSON 내려받기</button><button className={s.danger} onClick={()=>{if(window.confirm(`“${item.title}” 자산을 삭제할까요?`))void run(async()=>{await api({action:'delete',id:item.id});await refresh();setNotice('자산을 삭제했습니다.');});}}>삭제</button></div></article>)}{!items.some(i=>filter==='all'||i.kind===filter)&&<div className={s.empty}>아직 보관한 자산이 없습니다. 소재나 발행 계획을 먼저 저장해 보세요.</div>}</section>}
  </fieldset>
 </div>;
}
