import{test}from'node:test';import assert from'node:assert/strict';import{mkdtempSync}from'node:fs';import{tmpdir}from'node:os';import path from'node:path';
import{CoraStore}from'../lib/cora/store';import{BillingStore,PLANS,PACKS}from'../lib/cora/billing/credits';import{TossPayments}from'../lib/cora/billing/toss';

const DAY=86400000;
function setup(file=':memory:'){const s=new CoraStore(file),clock={t:Date.UTC(2026,8,1)};const b=s.module('billing',db=>new BillingStore(db,()=>clock.t));const u=s.signup('bill-a@example.test','password123'),v=s.signup('bill-b@example.test','password123');return{s,b,u,v,clock};}
const fake=(status:number,body:unknown,calls:{url:string;init:RequestInit}[]=[])=>(async(url:string|URL|Request,init?:RequestInit)=>{calls.push({url:String(url),init:init!});return new Response(JSON.stringify(body),{status});})as typeof fetch;

test('Billing: first use creates a 14-day trial with trial credits; prices default from code',()=>{const f=setup();try{const a=f.b.account(f.u.id);assert.equal(a.plan,'free');assert.equal(a.trialActive,true);assert.equal(a.trialDaysLeft,14);assert.equal(new Date(a.trialEnd).getTime()-Date.UTC(2026,8,1),14*DAY);assert.equal(a.balance,50);assert.equal(a.usage.runLimit,10);assert.equal(f.b.account(f.u.id).balance,50);assert.equal(f.b.history(f.u.id).length,1);assert.equal(f.b.quote(f.u.id,'card_ai'),10);assert.equal(f.b.quote(f.u.id,'publish'),1);f.clock.t+=15*DAY;assert.equal(f.b.account(f.u.id).trialActive,false);}finally{f.s.close();}});

test('Billing: grant, spend and refund move the balance and record balance after each row',()=>{const f=setup();try{f.b.grant(f.u.id,100,'테스트 지급');const sp=f.b.spend(f.u.id,'card_ai','k1','item-1');assert.ok(sp.ok);if(sp.ok){assert.equal(sp.entry.balanceAfter,140);assert.equal(sp.entry.itemId,'item-1');assert.equal(sp.entry.feature,'card_ai');}const r=f.b.refund(f.u.id,'k1','생성 실패');assert.equal(r.entry.balanceAfter,150);assert.equal(r.replay,false);assert.equal(f.b.refund(f.u.id,'k1','again').replay,true);assert.equal(f.b.account(f.u.id).balance,150);assert.deepEqual(f.b.history(f.u.id).map(h=>h.kind),['refund','spend','grant','grant']);assert.throws(()=>f.b.refund(f.u.id,'nope','x'),/찾을 수 없/);}finally{f.s.close();}});

test('Billing: insufficient credits returns a structured error and writes nothing; ledger is append-only',()=>{const f=setup();try{f.b.spend(f.u.id,'card_ai','a');f.b.spend(f.u.id,'card_ai','b');f.b.spend(f.u.id,'card_ai','c');f.b.spend(f.u.id,'card_ai','d');f.b.spend(f.u.id,'card_ai','e');assert.equal(f.b.account(f.u.id).balance,0);const n=f.b.history(f.u.id).length;const r=f.b.spend(f.u.id,'blog_ai','f');assert.deepEqual(r,{ok:false,code:'INSUFFICIENT_CREDITS',needed:8,balance:0});assert.equal(f.b.history(f.u.id).length,n);assert.equal(f.b.account(f.u.id).balance,0);assert.throws(()=>f.b.grant(f.u.id,0,'x'),/1 이상/);assert.throws(()=>f.b.spend(f.u.id,'nope','z'),/알 수 없는/);assert.throws(()=>f.b.spend(f.u.id,'card_ai',''),/중복 방지/);
 const db=(f.s as unknown as{db:import('node:sqlite').DatabaseSync}).db;assert.throws(()=>db.exec("UPDATE billing_ledger SET amount=0"),/append-only/);assert.throws(()=>db.exec('DELETE FROM billing_ledger'),/append-only/);}finally{f.s.close();}});

test('Billing: the same idempotency key twice writes one ledger row and charges once',()=>{const f=setup();try{const a=f.b.spend(f.u.id,'script_ai','same-key');const b=f.b.spend(f.u.id,'script_ai','same-key');assert.ok(a.ok&&b.ok);if(a.ok&&b.ok){assert.equal(a.replay,false);assert.equal(b.replay,true);assert.equal(a.entry.id,b.entry.id);}assert.equal(f.b.account(f.u.id).balance,44);assert.equal(f.b.history(f.u.id).filter(h=>h.kind==='spend').length,1);assert.throws(()=>f.b.spend(f.u.id,'card_ai','same-key'),/다른 기능/);const g1=f.b.grant(f.u.id,5,'x',{idempotencyKey:'g'}),g2=f.b.grant(f.u.id,5,'x',{idempotencyKey:'g'});assert.equal(g2.replay,true);assert.equal(g1.entry.id,g2.entry.id);}finally{f.s.close();}});

test('Billing: concurrent spends on two connections to one file never overdraw',async()=>{const dir=mkdtempSync(path.join(tmpdir(),'cora-bill-'));const file=path.join(dir,'db.sqlite');const f=setup(file);const s2=new CoraStore(file);const b2=s2.module('billing',db=>new BillingStore(db,()=>f.clock.t));try{f.b.account(f.u.id);const jobs:Promise<unknown>[]=[];const results:{ok:boolean}[]=[];for(let i=0;i<20;i++){const b=i%2?f.b:b2;jobs.push(new Promise<void>(r=>setImmediate(()=>{results.push(b.spend(f.u.id,'card_ai',`race-${i}`));r();})));}await Promise.all(jobs);assert.equal(results.filter(r=>r.ok).length,5);assert.equal(f.b.account(f.u.id).balance,0);assert.equal(b2.account(f.u.id).balance,0);const rows=f.b.history(f.u.id,100).filter(h=>h.kind==='spend');assert.equal(rows.length,5);assert.ok(f.b.history(f.u.id,100).every(h=>h.balanceAfter>=0));
 // a real cross-connection interleaving: hold the write lock on one connection, spend on the other after release
 const again=b2.spend(f.u.id,'card_ai','race-1');assert.ok(again.ok===false||again.replay);}finally{s2.close();f.s.close();}});

test('Billing: workspace owner can override a price; overrides are per user and bounded',()=>{const f=setup();try{f.b.setPrice(f.u.id,'card_ai',3);assert.equal(f.b.quote(f.u.id,'card_ai'),3);assert.equal(f.b.quote(f.v.id,'card_ai'),10);const sp=f.b.spend(f.u.id,'card_ai','p1');assert.ok(sp.ok&&sp.entry.amount===3);assert.equal(f.b.prices(f.u.id).find(p=>p.feature==='card_ai')!.overridden,true);assert.throws(()=>f.b.setPrice(f.u.id,'card_ai',-1),/0~1,000/);assert.throws(()=>f.b.setPrice(f.u.id,'x',1),/알 수 없는/);f.b.setPrice(f.u.id,'card_ai',null);assert.equal(f.b.quote(f.u.id,'card_ai'),10);}finally{f.s.close();}});

test('Billing: pack order completes once; only a paid observation grants; amount mismatch is refused',()=>{const f=setup();try{const o=f.b.createOrder(f.u.id,'pack','500');assert.equal(o.amount,PACKS[0].price);assert.match(o.orderId,/^cora-/);assert.equal(f.b.completeOrder(f.u.id,o.orderId,{status:'unknown',code:'NETWORK'}).order.status,'unknown');assert.equal(f.b.account(f.u.id).balance,50);assert.throws(()=>f.b.completeOrder(f.u.id,o.orderId,{status:'paid',amount:1}),/금액/);assert.equal(f.b.account(f.u.id).balance,50);const r1=f.b.completeOrder(f.u.id,o.orderId,{status:'paid',paymentKey:'pk',amount:o.amount});const r2=f.b.completeOrder(f.u.id,o.orderId,{status:'paid',paymentKey:'pk',amount:o.amount});assert.equal(r1.replay,false);assert.equal(r2.replay,true);assert.equal(f.b.account(f.u.id).balance,550);assert.equal(f.b.history(f.u.id,100).filter(h=>h.reason.includes('구매')).length,1);const bad=f.b.createOrder(f.u.id,'pack','1500');f.b.completeOrder(f.u.id,bad.orderId,{status:'failed',code:'REJECT_CARD_PAYMENT'});assert.equal(f.b.order(f.u.id,bad.orderId)!.status,'failed');assert.equal(f.b.account(f.u.id).balance,550);assert.throws(()=>f.b.createOrder(f.u.id,'pack','7'),/알 수 없는/);}finally{f.s.close();}});

test('Billing: plan upgrade applies on payment with prorated deduction; downgrade is scheduled to period end; lapse returns to free',()=>{const f=setup();try{const up=f.b.changePlan(f.u.id,'starter','monthly');assert.equal(up.action,'order');if(up.action!=='order')return;assert.equal(up.order.amount,PLANS.starter.monthly);assert.equal(f.b.account(f.u.id).plan,'free');f.b.completeOrder(f.u.id,up.order.orderId,{status:'paid',amount:up.order.amount});let a=f.b.account(f.u.id);assert.equal(a.plan,'starter');assert.equal(a.balance,350);f.clock.t+=15*DAY;const pro=f.b.changePlan(f.u.id,'pro','monthly');assert.equal(pro.action,'order');if(pro.action==='order'){assert.ok(pro.order.amount<PLANS.pro.monthly&&pro.order.amount>PLANS.pro.monthly-PLANS.starter.monthly);assert.match(pro.order.note,/차감/);f.b.completeOrder(f.u.id,pro.order.orderId,{status:'paid',amount:pro.order.amount});}assert.equal(f.b.account(f.u.id).plan,'pro');const down=f.b.changePlan(f.u.id,'starter','monthly');assert.equal(down.action,'scheduled');assert.equal(f.b.account(f.u.id).plan,'pro');assert.ok(f.b.account(f.u.id).pending);assert.equal(f.b.changePlan(f.u.id,'pro','monthly').action,'noop');assert.equal(f.b.account(f.u.id).pending,null);f.b.changePlan(f.u.id,'free','monthly');f.clock.t+=31*DAY;a=f.b.account(f.u.id);assert.equal(a.plan,'free');assert.equal(a.pending,null);}finally{f.s.close();}});

test('Billing: monthly grants for a paid plan are added once per 30 days inside the period',()=>{const f=setup();try{const up=f.b.changePlan(f.u.id,'starter','yearly');if(up.action!=='order')throw new Error('order');f.b.completeOrder(f.u.id,up.order.orderId,{status:'paid',amount:up.order.amount});assert.equal(f.b.account(f.u.id).balance,350);f.clock.t+=31*DAY;assert.equal(f.b.account(f.u.id).balance,650);assert.equal(f.b.account(f.u.id).balance,650);}finally{f.s.close();}});

test('Billing: users cannot see or complete each other orders, ledgers or balances',()=>{const f=setup();try{const o=f.b.createOrder(f.u.id,'pack','500');assert.equal(f.b.order(f.v.id,o.orderId),null);assert.throws(()=>f.b.completeOrder(f.v.id,o.orderId,{status:'paid'}),/NOT_FOUND/);f.b.spend(f.u.id,'card_ai','iso');assert.equal(f.b.account(f.v.id).balance,50);assert.equal(f.b.history(f.v.id).length,1);assert.equal(f.b.spend(f.v.id,'card_ai','iso').ok,true);assert.equal(f.b.account(f.u.id).balance,40);assert.equal(f.b.orders(f.v.id).length,0);}finally{f.s.close();}});

test('Toss: confirm sends POST with Basic auth, JSON body and maps DONE to paid',async()=>{const calls:{url:string;init:RequestInit}[]=[];const t=new TossPayments('test_sk_abc123',fake(200,{status:'DONE',orderId:'o1',totalAmount:5000},calls));const r=await t.confirm({paymentKey:'pk_1',orderId:'o1',amount:5000});assert.equal(r.status,'paid');assert.equal(calls.length,1);assert.equal(calls[0].url,'https://api.tosspayments.com/v1/payments/confirm');assert.equal(calls[0].init.method,'POST');const h=calls[0].init.headers as Record<string,string>;assert.equal(h.Authorization,'Basic '+Buffer.from('test_sk_abc123:').toString('base64'));assert.equal(h.Authorization,'Basic dGVzdF9za19hYmMxMjM6');assert.equal(h['Content-Type'],'application/json');assert.deepEqual(JSON.parse(String(calls[0].init.body)),{paymentKey:'pk_1',orderId:'o1',amount:5000});});

test('Toss: 4xx is failed with code, 5xx and thrown errors are unknown, never retried; mismatch and non-DONE are not paid; live keys are refused',async()=>{let c:{url:string;init:RequestInit}[]=[];const i={paymentKey:'pk',orderId:'o1',amount:5000};let r=await new TossPayments('test_sk_x',fake(400,{code:'REJECT_CARD_PAYMENT',message:'거절'},c)).confirm(i);assert.deepEqual([r.status,r.code],['failed','REJECT_CARD_PAYMENT']);assert.equal(c.length,1);c=[];r=await new TossPayments('test_sk_x',fake(500,{code:'FAILED_INTERNAL_SYSTEM_PROCESSING'},c)).confirm(i);assert.equal(r.status,'unknown');assert.equal(c.length,1);c=[];r=await new TossPayments('test_sk_x',(async()=>{c.push({url:'',init:{}});throw new Error('ECONNRESET');})as unknown as typeof fetch).confirm(i);assert.equal(r.status,'unknown');assert.equal(c.length,1);
 assert.equal((await new TossPayments('test_sk_x',fake(200,{status:'DONE',orderId:'o1',totalAmount:1})).confirm(i)).status,'unknown');assert.equal((await new TossPayments('test_sk_x',fake(200,{status:'IN_PROGRESS'})).confirm(i)).status,'unknown');assert.equal((await new TossPayments('test_sk_x',fake(200,{status:'ABORTED'})).confirm(i)).status,'failed');
 assert.throws(()=>new TossPayments('live_sk_abc',fake(200,{})),/테스트 키/);assert.throws(()=>new TossPayments('',fake(200,{})),/테스트 키/);await assert.rejects(new TossPayments('test_sk_x',fake(200,{})).confirm({...i,amount:0}),/필요/);});
