import{test}from'node:test';import assert from'node:assert/strict';import{mkdtempSync,rmSync}from'node:fs';import{tmpdir}from'node:os';import path from'node:path';
import{CoraStore}from'../lib/cora/store';import{outline,ideasFor,sampleBrief}from'../lib/cora/model';import{LEASE_MS,type Handler}from'../lib/cora/scheduler';import{schedulerHandlers}from'../lib/cora/scheduler-handlers';import type{SimulationProvider}from'../lib/cora/publishing/queue';

function setup(file=':memory:'){const s=new CoraStore(file),a=s.signup('sched-owner@example.test','password123'),b=s.signup('sched-review@example.test','password123'),other=s.signup('sched-other@example.test','password123');const draft=outline(sampleBrief,ideasFor(sampleBrief)[0]),p=s.save(a.id,draft)!,r=s.requestReview(a.id,p.id,1,b.email)!;s.decideReview(b.id,r.id,'approved','OK');const pub=s.preparePublication(a.id,r.id,'brand','');const queueId=s.publicationQueue.enqueue(a.id,pub.id,0);const recipe=s.addItem(a.id,'automation','주간 대본',{prompt:'매주 대본',frequency:'weekly',brand:'책방'});return{s,a,b,other,p,r,pub,queueId,recipe};}
const provider:SimulationProvider={async submit(){return{state:'submitted',submissionId:'sub-1'};},async status(id){return{state:'published',submissionId:id,publicUrl:'https://example.test/post'};}};
const ok:Handler=async()=>'ok';

test('Scheduler: same target is not duplicated, other users cannot see or control a job, invalid targets are refused',()=>{const f=setup();try{const sch=f.s.scheduler;const first=sch.schedule(f.a.id,{kind:'publication_tick',refId:f.queueId,intervalMs:10000},0);assert.equal(first.created,true);const again=sch.schedule(f.a.id,{kind:'publication_tick',refId:f.queueId,intervalMs:10000},5);assert.deepEqual(again,{id:first.id,created:false});assert.equal(sch.list(f.a.id).length,1);assert.equal(sch.list(f.other.id).length,0);assert.equal(sch.pause(f.other.id,first.id),false);assert.equal(sch.cancel(f.other.id,first.id),false);assert.throws(()=>sch.runs(f.other.id,first.id),/NOT_FOUND/);assert.throws(()=>sch.schedule(f.other.id,{kind:'publication_tick',refId:f.queueId}),/찾을 수 없습니다/);assert.throws(()=>sch.schedule(f.a.id,{kind:'recipe_run',refId:'missing'}),/찾을 수 없습니다/);assert.throws(()=>sch.schedule(f.a.id,{kind:'recipe_run',refId:f.recipe.id,intervalMs:1000}),/반복 간격/);}finally{f.s.close();}});

test('Scheduler: jobs and run history survive reopening the database file',async()=>{const dir=mkdtempSync(path.join(tmpdir(),'cora-sched-'));const file=path.join(dir,'db.sqlite');let f=setup(file);try{const id=f.s.scheduler.schedule(f.a.id,{kind:'recipe_run',refId:f.recipe.id,intervalMs:86400000},1000).id;await f.s.scheduler.runDue({recipe_run:ok},{now:1000});f.s.close();const s=new CoraStore(file);try{const job=s.scheduler.list(f.a.id)[0];assert.equal(job.id,id);assert.equal(job.state,'active');assert.equal(job.runAt,1000+86400000);assert.equal(s.scheduler.runs(f.a.id,id)[0].outcome,'ok');}finally{s.close();}}finally{rmSync(dir,{recursive:true,force:true});}});

test('Scheduler: a leased job is not claimed twice; an expired lease counts as a failed attempt and a stale finish is ignored',async()=>{const f=setup();try{const sch=f.s.scheduler;const id=sch.schedule(f.a.id,{kind:'recipe_run',refId:f.recipe.id,intervalMs:60000,maxAttempts:2},0).id;const[claim]=sch.claimDue(0);assert.equal(claim.id,id);assert.equal(sch.claimDue(1).length,0);const[reclaim]=sch.claimDue(LEASE_MS+1);assert.equal(reclaim.id,id);assert.equal(reclaim.attempts,1);assert.equal(sch.finish(claim,{outcome:'ok'},0,LEASE_MS+2),false);assert.equal(sch.runs(f.a.id,id)[0].outcome,'lease_expired');sch.claimDue(2*LEASE_MS+2);assert.equal(sch.list(f.a.id)[0].state,'failed');}finally{f.s.close();}});

test('Scheduler: failures back off then stop at max attempts; resume clears attempts; skipped keeps the recurring slot',async()=>{const f=setup();try{const sch=f.s.scheduler;const id=sch.schedule(f.a.id,{kind:'recipe_run',refId:f.recipe.id,intervalMs:3600000,maxAttempts:3},0).id;const boom:Handler=async()=>{throw new Error('provider secret text');};await sch.runDue({recipe_run:boom},{now:0});let job=sch.list(f.a.id)[0];assert.equal(job.attempts,1);assert.equal(job.state,'active');assert.equal(job.runAt,2*LEASE_MS);assert.equal(sch.claimDue(1).length,0);await sch.runDue({recipe_run:boom},{now:job.runAt});await sch.runDue({recipe_run:boom},{now:sch.list(f.a.id)[0].runAt});job=sch.list(f.a.id)[0];assert.equal(job.state,'failed');assert.equal(job.attempts,3);assert.equal(sch.runs(f.a.id,id).length,3);assert.ok(sch.runs(f.a.id,id).every(r=>r.outcome==='failed'));assert.equal(sch.resume(f.a.id,id,5000000),true);job=sch.list(f.a.id)[0];assert.equal(job.state,'active');assert.equal(job.attempts,0);assert.ok(job.runAt>=5000000);const skip:Handler=async()=>'skipped';await sch.runDue({recipe_run:skip},{now:job.runAt});const next=sch.list(f.a.id)[0];assert.equal(next.state,'active');assert.equal(next.runAt,job.runAt+3600000);assert.equal(next.lastOutcome,'skipped');}finally{f.s.close();}});

test('Scheduler: one-off jobs finish after success; recurring jobs skip missed slots instead of bursting',async()=>{const f=setup();try{const sch=f.s.scheduler;const once=sch.schedule(f.a.id,{kind:'recipe_run',refId:f.recipe.id},100).id;await sch.runDue({recipe_run:ok},{now:100});assert.equal(sch.list(f.a.id)[0].state,'done');const cancelled=sch.cancel(f.a.id,once);assert.equal(cancelled,false);const rec=sch.schedule(f.a.id,{kind:'recipe_run',refId:f.recipe.id,intervalMs:10000},1000).id;await sch.runDue({recipe_run:ok},{now:1000+45000});assert.equal(sch.list(f.a.id).find(j=>j.id===rec)!.runAt,1000+50000);}finally{f.s.close();}});

test('Scheduler: publication tick drives the simulation queue to a terminal state, then completes without polling forever',async()=>{const f=setup();try{const sch=f.s.scheduler;const h=schedulerHandlers(f.s,{mode:'labs',provider});const id=sch.schedule(f.a.id,{kind:'publication_tick',refId:f.queueId,intervalMs:10000},0).id;await sch.runDue(h,{now:0});assert.equal(f.s.publicationQueue.get(f.a.id,f.queueId)!.state,'submitted');assert.equal(sch.list(f.a.id)[0].state,'active');await sch.runDue(h,{now:10000});assert.equal(f.s.publicationQueue.get(f.a.id,f.queueId)!.state,'published');assert.equal(sch.list(f.a.id)[0].state,'done');assert.equal(sch.runs(f.a.id,id)[0].outcome,'completed');const cancelledQueue=f.s.publicationQueue.enqueue(f.a.id,f.pub.id,0);assert.equal(cancelledQueue,f.queueId);}finally{f.s.close();}});

test('Scheduler: recipe runs never call paid AI unless the job and the process both allow it; results are saved as assets',async()=>{const f=setup();try{const sch=f.s.scheduler;let calls=0;const generate=async()=>{calls++;return{text:'생성된 대본',provider:'test',model:'test',cost:null};};const id=sch.schedule(f.a.id,{kind:'recipe_run',refId:f.recipe.id,intervalMs:86400000,payload:{format:'script',material:'책방 신간 소식 열 글자 이상의 자료'}},0).id;await sch.runDue(schedulerHandlers(f.s,{mode:'labs',generate,aiEnabled:true}),{now:0});assert.equal(calls,0);assert.match(sch.runs(f.a.id,id)[0].detail,/허용하지 않았습니다/);assert.equal(sch.setAiAllowed(f.other.id,id,true),false);assert.equal(sch.setAiAllowed(f.a.id,id,true),true);await sch.runDue(schedulerHandlers(f.s,{mode:'labs',generate,aiEnabled:false}),{now:86400000});assert.equal(calls,0);assert.match(sch.runs(f.a.id,id)[0].detail,/CORA_SCHEDULER_AI/);await sch.runDue(schedulerHandlers(f.s,{mode:'labs',generate,aiEnabled:true}),{now:2*86400000});assert.equal(calls,1);const saved=f.s.items(f.a.id).find(i=>i.kind==='script');assert.ok(saved);assert.equal(saved!.data.automated,true);assert.equal(saved!.data.recipeId,f.recipe.id);assert.equal(f.s.generationCount(f.a.id),1);await sch.runDue(schedulerHandlers(f.s,{mode:'labs',generate,aiEnabled:true,dailyLimit:1}),{now:3*86400000});assert.equal(calls,1);assert.match(sch.runs(f.a.id,id)[0].detail,/한도/);f.s.removeItem(f.a.id,f.recipe.id);await sch.runDue(schedulerHandlers(f.s,{mode:'labs',generate,aiEnabled:true}),{now:4*86400000});assert.equal(sch.list(f.a.id)[0].state,'done');}finally{f.s.close();}});

test('Scheduler: two connections to one file never run the same job concurrently',async()=>{const dir=mkdtempSync(path.join(tmpdir(),'cora-sched2-'));const file=path.join(dir,'db.sqlite');const f=setup(file);const second=new CoraStore(file);try{const id=f.s.scheduler.schedule(f.a.id,{kind:'recipe_run',refId:f.recipe.id,intervalMs:60000},0).id;let running=0,max=0;const slow:Handler=async()=>{running++;max=Math.max(max,running);await new Promise(r=>setTimeout(r,30));running--;return'ok';};await Promise.all([f.s.scheduler.runDue({recipe_run:slow},{now:0}),second.scheduler.runDue({recipe_run:slow},{now:1})]);assert.equal(max,1);assert.equal(second.scheduler.runs(f.a.id,id).length,1);}finally{second.close();f.s.close();rmSync(dir,{recursive:true,force:true});}});
