import{test}from'node:test';import assert from'node:assert/strict';import{InstagramAdapter,validateInstagramInput,IG_API_VERSION}from'../lib/cora/publishing/instagram';
type Call={method:string;path:string;params:Record<string,string>;auth:string};
function fake(routes:(c:Call)=>{status?:number;body?:unknown}|'throw'){const calls:Call[]=[];const transport=async(url:any,init:any)=>{const u=new URL(String(url));const params:Record<string,string>=init.method==='GET'?Object.fromEntries(u.searchParams):Object.fromEntries(new URLSearchParams(String(init.body)));const c={method:init.method,path:u.pathname.replace(`/${IG_API_VERSION}/`,''),params,auth:init.headers.Authorization};calls.push(c);const r=routes(c);if(r==='throw')throw new Error('socket hang up token=SECRET');return new Response(JSON.stringify(r.body??{}),{status:r.status??200});};return{calls,transport:transport as typeof fetch};}
const one={igUserId:'1784',caption:'승인된 캡션 #책방',imageUrls:['https://cdn.example.test/a.jpg']};

test('Instagram input: JPEG on public HTTPS only, 1~10 images, caption and hashtag limits',()=>{assert.ok(validateInstagramInput(one));for(const url of['https://cdn.example.test/a.png','http://cdn.example.test/a.jpg','https://127.0.0.1/a.jpg','https://u:p@cdn.example.test/a.jpg','https://localhost/a.jpg'])assert.throws(()=>validateInstagramInput({...one,imageUrls:[url]}));assert.throws(()=>validateInstagramInput({...one,imageUrls:[]}));assert.throws(()=>validateInstagramInput({...one,imageUrls:Array(11).fill(one.imageUrls[0])}));assert.throws(()=>validateInstagramInput({...one,caption:'x'.repeat(2201)}));assert.throws(()=>validateInstagramInput({...one,caption:Array(31).fill('#t').join(' ')}));assert.throws(()=>validateInstagramInput({...one,igUserId:'abc'}));assert.throws(()=>new InstagramAdapter(''));});

test('Instagram submit creates containers only (single and carousel); token only in Authorization header',async()=>{let n=100;const f=fake(()=>({body:{id:String(n++)}}));const a=new InstagramAdapter('TOKEN-not-real',f.transport);const r=await a.submit(one);assert.deepEqual(r,{state:'submitted',submissionId:'1784_100'});assert.equal(f.calls.length,1);assert.equal(f.calls[0].path,'1784/media');assert.equal(f.calls[0].params.image_url,one.imageUrls[0]);assert.equal(f.calls[0].auth,'Bearer TOKEN-not-real');assert.ok(!JSON.stringify(f.calls.map(c=>c.params)).includes('TOKEN'));assert.ok(!f.calls.some(c=>c.path.endsWith('media_publish')));
 const g=fake(c=>({body:{id:c.params.media_type==='CAROUSEL'?'900':String(n++)}}));const car=await new InstagramAdapter('T',g.transport).submit({...one,imageUrls:['https://cdn.example.test/1.jpg','https://cdn.example.test/2.jpg','https://cdn.example.test/3.jpg']});assert.equal(car.submissionId,'1784_900');assert.equal(g.calls.length,4);assert.ok(g.calls.slice(0,3).every(c=>c.params.is_carousel_item==='true'&&!c.params.caption));assert.equal(g.calls[3].params.children.split(',').length,3);assert.equal(g.calls[3].params.caption,one.caption);});

test('Instagram submit failures: 4xx is failed, 5xx/429/network is unknown, private error text never leaks',async()=>{for(const[status,state]of[[400,'failed'],[429,'unknown'],[500,'unknown']]as const){const r=await new InstagramAdapter('T',fake(()=>({status,body:{error:{message:'secret'}}})).transport).submit(one);assert.equal(r.state,state);}const r=await new InstagramAdapter('T',fake(()=>'throw').transport).submit(one);assert.equal(r.state,'unknown');assert.ok(!JSON.stringify(r).includes('SECRET'));});

test('Instagram status: IN_PROGRESS waits, FINISHED publishes once and returns permalink, ERROR/EXPIRED fail',async()=>{let code='IN_PROGRESS';const f=fake(c=>c.path==='555'?{body:{status_code:code}}:c.path==='1784/media_publish'?{body:{id:'777'}}:c.path==='777'?{body:{permalink:'https://www.instagram.com/p/ABC/'}}:{status:404});const a=new InstagramAdapter('T',f.transport);assert.equal((await a.status('1784_555')).state,'submitted');assert.equal(f.calls.filter(c=>c.path.endsWith('media_publish')).length,0);code='FINISHED';const r=await a.status('1784_555');assert.deepEqual(r,{state:'published',submissionId:'1784_555',publicUrl:'https://www.instagram.com/p/ABC/'});const pub=f.calls.filter(c=>c.path.endsWith('media_publish'));assert.equal(pub.length,1);assert.equal(pub[0].params.creation_id,'555');for(const c of['ERROR','EXPIRED']){code=c;assert.equal((await a.status('1784_555')).state,'failed');}await assert.rejects(()=>a.status('bad id'));});

test('Instagram status: lost publish response never double-posts; PUBLISHED container stays unknown; non-Instagram permalink rejected',async()=>{let code='FINISHED',publishCalls=0;const f=fake(c=>{if(c.path==='555')return{body:{status_code:code}};if(c.path.endsWith('media_publish')){publishCalls++;code='PUBLISHED';return'throw';}return{status:404};});const a=new InstagramAdapter('T',f.transport);assert.equal((await a.status('1784_555')).state,'unknown');const again=await a.status('1784_555');assert.equal(again.state,'unknown');assert.match(again.reason!,/직접 확인/);assert.equal(publishCalls,1);
 const g=fake(c=>c.path==='556'?{body:{status_code:'FINISHED'}}:c.path.endsWith('media_publish')?{body:{id:'778'}}:{body:{permalink:'https://evil.example/p/1'}});const r=await new InstagramAdapter('T',g.transport).status('1784_556');assert.equal(r.state,'unknown');assert.match(r.reason!,/778/);});

test('Instagram quota reads the 24h publishing limit',async()=>{const f=fake(()=>({body:{data:[{quota_usage:3,config:{quota_total:100}}]}}));assert.deepEqual(await new InstagramAdapter('T',f.transport).quota('1784'),{used:3,total:100});assert.equal(f.calls[0].path,'1784/content_publishing_limit');});
