import{test}from'node:test';import assert from'node:assert/strict';
import{CoraStore}from'../lib/cora/store';import{outline,ideasFor,sampleBrief}from'../lib/cora/model';

function setup(){const s=new CoraStore(':memory:'),owner=s.signup('team-owner@example.test','password123'),ed=s.signup('team-editor@example.test','password123'),rv=s.signup('team-reviewer@example.test','password123'),out=s.signup('team-outsider@example.test','password123');
 const book=outline(sampleBrief,ideasFor(sampleBrief)[0]),cafe={...outline({...sampleBrief,brand:'골목 카페'},ideasFor({...sampleBrief,brand:'골목 카페'})[0])};
 const pBook=s.save(owner.id,book)!,pCafe=s.save(owner.id,cafe)!;return{s,owner,ed,rv,out,book,cafe,pBook,pCafe};}

test('Team: invitation grants nothing until accepted; outsiders and self-invites are refused',()=>{const f=setup();try{const t=f.s.team;assert.throws(()=>t.invite(f.owner.id,'team-owner@example.test','editor'),/다른 사람/);assert.throws(()=>t.invite(f.owner.id,'nobody@example.test','editor'),/다른 사람/);assert.throws(()=>t.invite(f.owner.id,f.ed.email,'admin'),/역할/);const inv=t.invite(f.owner.id,f.ed.email,'editor');assert.equal(inv.status,'invited');assert.equal(f.s.getAccessible(f.ed.id,f.pBook.id),null);assert.deepEqual(f.s.sharedProjects(f.ed.id),[]);assert.throws(()=>t.respond(f.out.id,inv.id,true),/NOT_FOUND/);t.respond(f.ed.id,inv.id,true);const p=f.s.getAccessible(f.ed.id,f.pBook.id)!;assert.equal(p.access,'editor');assert.equal(p.ownerEmail,f.owner.email);assert.equal(f.s.sharedProjects(f.ed.id).length,2);assert.equal(f.s.getAccessible(f.out.id,f.pBook.id),null);assert.throws(()=>t.respond(f.ed.id,inv.id,true),/NOT_FOUND/);}finally{f.s.close();}});

test('Team: editor saves with version conflict protection; the change lands on the owner project and owner sees it',()=>{const f=setup();try{const t=f.s.team;t.respond(f.ed.id,t.invite(f.owner.id,f.ed.email,'editor').id,true);const saved=f.s.saveAccessible(f.ed.id,{...f.book,caption:'편집자가 고친 캡션'},f.pBook.id,1)!;assert.equal(saved.version,2);assert.equal(f.s.get(f.owner.id,f.pBook.id)!.caption,'편집자가 고친 캡션');assert.throws(()=>f.s.saveAccessible(f.owner.id,{...f.book,caption:'오래된 창'},f.pBook.id,1),/CONFLICT/);assert.equal(f.s.list(f.ed.id).length,0);}finally{f.s.close();}});

test('Team: brand-limited editor sees and edits only granted brands and cannot move work out of them',()=>{const f=setup();try{const t=f.s.team;t.respond(f.ed.id,t.invite(f.owner.id,f.ed.email,'editor',['모퉁이 책방']).id,true);assert.deepEqual(f.s.sharedProjects(f.ed.id).map(p=>p.brand),['모퉁이 책방']);assert.equal(f.s.getAccessible(f.ed.id,f.pCafe.id),null);assert.equal(f.s.saveAccessible(f.ed.id,f.cafe,f.pCafe.id,1),null);assert.throws(()=>f.s.saveAccessible(f.ed.id,{...f.book,brief:{...f.book.brief,brand:'골목 카페'}},f.pBook.id,1),/권한이 없는 브랜드/);assert.throws(()=>t.invite(f.owner.id,f.ed.email,'editor','책방'),/형식/);}finally{f.s.close();}});

test('Team: reviewers cannot edit; owner-only actions stay owner-only for editors',()=>{const f=setup();try{const t=f.s.team;t.respond(f.rv.id,t.invite(f.owner.id,f.rv.email,'reviewer').id,true);t.respond(f.ed.id,t.invite(f.owner.id,f.ed.email,'editor').id,true);assert.equal(f.s.getAccessible(f.rv.id,f.pBook.id),null);assert.deepEqual(f.s.team.reviewerSuggestions(f.owner.id),[f.rv.email,f.ed.email]);assert.equal(f.s.delete(f.ed.id,f.pBook.id,1),false);assert.throws(()=>f.s.requestReview(f.ed.id,f.pBook.id,1,f.rv.email),/NOT_FOUND/);assert.ok(f.s.get(f.owner.id,f.pBook.id));}finally{f.s.close();}});

test('Team: removal and leaving end access immediately; re-invite requires acceptance again; role changes apply',()=>{const f=setup();try{const t=f.s.team;const id=t.invite(f.owner.id,f.ed.email,'editor').id;t.respond(f.ed.id,id,true);assert.ok(f.s.getAccessible(f.ed.id,f.pBook.id));t.update(f.owner.id,id,'reviewer',[]);assert.equal(f.s.getAccessible(f.ed.id,f.pBook.id),null);t.update(f.owner.id,id,'editor',[]);assert.ok(f.s.getAccessible(f.ed.id,f.pBook.id));assert.throws(()=>t.update(f.out.id,id,'editor',[]),/NOT_FOUND/);assert.throws(()=>t.remove(f.out.id,id),/NOT_FOUND/);t.remove(f.owner.id,id);assert.equal(f.s.getAccessible(f.ed.id,f.pBook.id),null);assert.equal(f.s.saveAccessible(f.ed.id,f.book,f.pBook.id,1),null);assert.equal(t.overview(f.owner.id).members.length,0);const again=t.invite(f.owner.id,f.ed.email,'editor');assert.equal(again.id,id);assert.equal(again.status,'invited');assert.equal(f.s.getAccessible(f.ed.id,f.pBook.id),null);t.respond(f.ed.id,id,true);t.remove(f.ed.id,id);assert.equal(f.s.getAccessible(f.ed.id,f.pBook.id),null);const declined=t.invite(f.owner.id,f.ed.email,'editor');t.respond(f.ed.id,declined.id,false);assert.equal(t.overview(f.owner.id).members[0].status,'declined');assert.equal(t.overview(f.ed.id).memberships.length,0);}finally{f.s.close();}});
