import{test}from'node:test';import assert from'node:assert/strict';import{mkdtempSync,rmSync}from'node:fs';import{tmpdir}from'node:os';import path from'node:path';
import{CoraStore}from'../lib/cora/store';import{createOutline,approveOutline,reopenOutline,writeFromOutline,claimWriting,WRITING_LEASE_MS}from'../lib/cora/blog-outline';
const gen=(texts:string[])=>{let n=0;const calls:string[]=[];return{calls,fn:async(_u:string,p:string)=>{calls.push(p);return{text:texts[n++]??'x',provider:'test',model:'test',cost:null};}};};
function setup(file=':memory:'){const s=new CoraStore(file);const a=s.signup('outline-a@example.test','password123'),b=s.signup('outline-b@example.test','password123');return{s,a,b};}
test('Outline: created as draft; approval requires the seen text, happens once, and stores the edited plan',async()=>{const{s,a,b}=setup();try{const g=gen(['## 개요 초안']);const o=await createOutline(s,a.id,{material:'책방 모임 소개 자료 열 글자 이상',brand:'책방'},g.fn);assert.equal(o.data.status,'draft');assert.match(g.calls[0],/개요만/);assert.throws(()=>approveOutline(s,a.id,o.id,'다른 화면의 글','수정'),/STALE/);assert.throws(()=>approveOutline(s,b.id,o.id,'## 개요 초안','x'),/NOT_FOUND/);const ok=approveOutline(s,a.id,o.id,'## 개요 초안','## 고친 개요');assert.equal(ok.data.status,'approved');assert.equal(ok.data.text,'## 고친 개요');assert.equal(ok.data.humanEdited,true);assert.throws(()=>approveOutline(s,a.id,o.id,'## 고친 개요','again'),/ALREADY_APPROVED/);assert.equal(reopenOutline(s,a.id,o.id).data.status,'draft');await assert.rejects(()=>createOutline(s,a.id,{material:'짧음'},g.fn),/10자/);}finally{s.close();}});
test('Outline: body uses the approved text once; a second write is refused; failures release the claim',async()=>{const{s,a}=setup();try{const g=gen(['개요','본문 결과']);const o=await createOutline(s,a.id,{material:'책방 모임 소개 자료 열 글자 이상'},g.fn);await assert.rejects(()=>writeFromOutline(s,a.id,o.id,g.fn),/NOT_APPROVED/);approveOutline(s,a.id,o.id,'개요','승인된 개요 텍스트');const blog=await writeFromOutline(s,a.id,o.id,g.fn);assert.equal(blog.kind,'blog');assert.equal(blog.data.outlineId,o.id);assert.match(g.calls[1],/승인된 개요 텍스트/);assert.equal(s.item(a.id,o.id)!.data.status,'written');await assert.rejects(()=>writeFromOutline(s,a.id,o.id,g.fn),/WRITTEN/);assert.equal(g.calls.length,2);
 const o2=await createOutline(s,a.id,{material:'두 번째 자료 열 글자 이상입니다'},gen(['개요2']).fn);approveOutline(s,a.id,o2.id,'개요2','개요2');const boom=async()=>{throw new Error('gateway down');};await assert.rejects(()=>writeFromOutline(s,a.id,o2.id,boom),/gateway/);const after=s.item(a.id,o2.id)!;assert.equal(after.data.status,'approved');assert.match(String(after.data.lastError),/자동 재시도하지 않습니다/);}finally{s.close();}});
test('Outline: concurrent writes on two connections claim once; a stale writing claim can be reclaimed',async()=>{const dir=mkdtempSync(path.join(tmpdir(),'cora-outline-'));const file=path.join(dir,'db.sqlite');const f=setup(file);const second=new CoraStore(file);try{const o=await createOutline(f.s,f.a.id,{material:'동시 작성 시험 자료 열 글자 이상'},gen(['개요']).fn);approveOutline(f.s,f.a.id,o.id,'개요','개요');let release!:()=>void;let calls=0;const slow=async()=>{calls++;await new Promise<void>(r=>release=r);return{text:'본문',provider:'t',model:'t',cost:null};};const first=writeFromOutline(f.s,f.a.id,o.id,slow);await assert.rejects(()=>writeFromOutline(second,f.a.id,o.id,slow),/WRITING/);release();await first;assert.equal(calls,1);
 const o3=await createOutline(f.s,f.a.id,{material:'멈춘 작성 시험 자료 열 글자 이상'},gen(['개요']).fn);approveOutline(f.s,f.a.id,o3.id,'개요','개요');claimWriting(f.s,f.a.id,o3.id,1000);assert.throws(()=>claimWriting(f.s,f.a.id,o3.id,1000+WRITING_LEASE_MS-1),/WRITING/);assert.equal(claimWriting(f.s,f.a.id,o3.id,1000+WRITING_LEASE_MS+1).data.status,'writing');}finally{second.close();f.s.close();rmSync(dir,{recursive:true,force:true});}});
