"""Generate reviewable contracts only; no production DB or API changes."""
import json
from pathlib import Path

OUT = Path(__file__).parent / "proposedcontracts.json"
tables = []


def f(kind="text", nullable=False, note=None, enum=None):
    d = {"type": kind, "nullable": nullable}
    if note:
        d["description"] = note
    if enum:
        d["enum"] = enum.split("|")
    return d


def ref(table, nullable=False, note=None):
    d = f("uuid", nullable, note)
    d["references"] = table
    return d


def t(name, phase, fields, *, scope="tenant", retention="customer_workspace", immutable=False, unique=None, checks=None, note=""):
    columns = {"id": f("uuid")}
    if scope == "tenant":
        columns["tenant_id"] = ref("tenants")
    columns.update(fields)
    columns["created_at"] = f("timestamptz")
    if not immutable:
        columns["updated_at"] = f("timestamptz")
    tables.append({
        "name": name,
        "phase": phase,
        "scope": scope,
        "description": note,
        "primary_key": ["tenant_id", "id"] if scope == "tenant" else ["id"],
        "columns": columns,
        "unique_constraints": unique or [],
        "check_contracts": checks or [],
        "append_only": immutable,
        "retention_policy": retention,
        "access": "verified_tenant_and_brand_grants_plus_RLS" if scope == "tenant" else "restricted_control_plane_or_public_definitions_only",
    })


t("tenants", "P0", {
    "name": f(), "kind": f(enum="agency|creator"), "status": f(enum="trial|active|suspended|deleting|deleted"),
    "default_timezone": f(note="IANA timezone"), "plan_code": f(), "data_region": f(),
}, scope="control", unique=[["id"]], note="Billing workspace. Creator has one initial brand; agency may have several.")
t("users", "P0", {"auth_provider": f(), "auth_subject": f(), "status": f(enum="active|disabled|deleted")}, scope="control", unique=[["auth_provider", "auth_subject"]], retention="identity", note="Authentication identity only, not a tenant or brand entitlement.")
t("memberships", "P0", {"user_id": ref("users"), "role": f(enum="owner|admin|editor|reviewer|analyst|billing_manager"), "status": f(enum="invited|active|revoked"), "revoked_at": f("timestamptz", True)}, unique=[["tenant_id", "user_id"]])
t("brands", "P0", {"name": f(), "status": f(enum="active|archived|deleting"), "timezone": f(), "client_reference": f(nullable=True)})
t("brand_grants", "P0", {"membership_id": ref("memberships"), "brand_id": ref("brands"), "actions": f("text[]", note="view,draft,edit,review,connect,analyze,publish,manage_brand"), "expires_at": f("timestamptz", True), "revoked_at": f("timestamptz", True)}, unique=[["tenant_id", "membership_id", "brand_id"]])
t("brand_profile_versions", "P0", {"brand_id": ref("brands"), "version": f("integer"), "profile": f("jsonb", note="audience, tone, prohibited claims, brand assets, source references"), "digest": f(), "created_by": ref("users")}, unique=[["tenant_id", "brand_id", "version"]], immutable=True)
t("goals", "P0", {"brand_id": ref("brands"), "version": f("integer"), "objective": f(enum="awareness|saves|leads|sales_support|consistency|other"), "target_audience": f(), "success_definition": f("jsonb"), "production_constraints": f("jsonb"), "active_from": f("timestamptz"), "active_to": f("timestamptz", True)}, immutable=True)
t("consents", "P0", {"actor_user_id": ref("users"), "brand_id": ref("brands", True), "purpose": f(), "document_version": f(), "granted_at": f("timestamptz"), "revoked_at": f("timestamptz", True), "evidence_hash": f(), "provider_clearance_required": f("boolean")}, retention="consent_evidence", note="Customer consent is distinct from provider permission; not sufficient to authorize cross-client Meta training.")
t("rights_grants", "P0", {"purpose": f(enum="process_for_user|benchmark|train|reuse_media|publish"), "status": f(enum="allowed|denied|pending|expired|revoked"), "provider": f(nullable=True), "provider_policy_version": f(nullable=True), "provider_clearance": f(enum="not_applicable|verified_allowed|pending|denied"), "clearance_evidence_ref": f(nullable=True), "license_evidence_ref": f(nullable=True), "customer_instruction_ref": f(nullable=True), "consent_id": ref("consents", True), "valid_from": f("timestamptz"), "expires_at": f("timestamptz", True), "restrictions": f("jsonb"), "reviewed_by": ref("users", True)}, retention="rights_evidence", checks=["allowed requires all applicable provider, customer instruction and media-license conditions; consent alone cannot override provider denial", "Meta customer data cross-client training/benchmarking denied by default", "YouTube derived metrics disabled unless the relevant use case is accepted and conditions met"])
t("rights_bindings", "P0", {"rights_grant_id": ref("rights_grants"), "source_item_id": ref("source_items", True), "social_account_id": ref("social_accounts", True), "artifact_version_id": ref("artifact_versions", True)}, immutable=True, checks=["exactly one of source_item_id,social_account_id,artifact_version_id is non-null"], note="Explicit resource FK; inherited rights must be evaluated through lineage before execution.")
t("deletion_requests", "P0", {"requested_by": ref("users"), "brand_id": ref("brands", True), "scope": f(enum="tenant|brand|connection|source|artifact|model_purpose"), "resource_id": f("uuid", True, note="Resource must resolve inside tenant under the named scope"), "status": f(enum="received|access_blocked|online_deleted|backup_expiry_pending|completed|blocked_legal"), "requested_at": f("timestamptz"), "due_at": f("timestamptz", True), "completed_at": f("timestamptz", True), "lineage_actions": f("jsonb"), "legal_hold_reason": f(nullable=True)}, retention="deletion_evidence")

t("external_connections", "P1", {"brand_id": ref("brands"), "provider": f(enum="instagram_login|facebook_login|youtube|other"), "provider_subject": f(), "api_version": f(), "token_vault_ref": f(nullable=True, note="Opaque reference only, no raw token"), "granted_scopes": f("text[]"), "permission_status": f(enum="development_only|review_pending|production_approved|revoked|expired"), "connected_by": ref("users"), "consent_id": ref("consents"), "expires_at": f("timestamptz", True), "revoked_at": f("timestamptz", True), "last_success_at": f("timestamptz", True)}, unique=[["tenant_id", "brand_id", "provider", "provider_subject"]], retention="connection", checks=["revoked/expired connection cannot schedule or execute collection/publishing", "external customer availability requires the applicable approved access level"])
t("social_accounts", "P1", {"brand_id": ref("brands"), "connection_id": ref("external_connections", True), "platform": f(), "external_account_id": f(), "handle": f(nullable=True), "account_type": f(enum="business|creator|personal|unknown"), "capabilities": f("jsonb"), "source_type": f(enum="provider_api|customer_import|customer_manual"), "history_started_at": f("timestamptz", True)}, unique=[["tenant_id", "brand_id", "platform", "external_account_id"], ["tenant_id", "brand_id", "id"]], note="A customer-import account is not an OAuth connection. Connection ownership must match brand.")
t("source_items", "P0", {"brand_id": ref("brands"), "kind": f(enum="customer_upload|licensed_library|provider_metadata|article_reference|customer_note"), "uri": f(nullable=True), "private_object_key": f(nullable=True), "content_hash": f(nullable=True), "source_provider": f(nullable=True), "external_id": f(nullable=True), "acquired_at": f("timestamptz"), "event_time": f("timestamptz", True), "available_at": f("timestamptz"), "refresh_due_at": f("timestamptz", True), "delete_due_at": f("timestamptz", True), "license_summary": f(nullable=True), "metadata": f("jsonb")}, retention="source_specific", note="No universal license inferred from a public URL.")
t("content_posts", "P1", {"brand_id": ref("brands"), "social_account_id": ref("social_accounts"), "artifact_version_id": ref("artifact_versions", True), "platform": f(), "external_post_id": f(), "permalink": f(nullable=True), "published_at": f("timestamptz"), "media_format": f(enum="carousel|image|reel|story|video|text|unknown"), "paid_status": f(enum="organic_confirmed|promoted_confirmed|mixed|unknown"), "collaboration_status": f(enum="yes|no|unknown"), "caption_source_item_id": ref("source_items", True), "deleted_at": f("timestamptz", True)}, unique=[["tenant_id", "social_account_id", "external_post_id"]], retention="provider_specific", checks=["social account brand matches brand_id", "artifact_version belongs to same brand if present"])
t("metric_definitions", "P1", {"provider": f(), "api_version": f(), "metric_key": f(), "entity_level": f(enum="account|post"), "unit": f(), "aggregation": f(enum="count|sum|average|ratio|estimated_unique|other"), "denominator_definition": f(nullable=True), "organic_paid_scope": f(), "supported_formats": f("text[]"), "period_semantics": f(), "availability_rules": f("jsonb"), "definition_version": f(), "official_source_url": f()}, scope="catalog", immutable=True, unique=[["provider", "api_version", "metric_key", "entity_level", "definition_version"]], retention="definition_catalog")
t("metric_snapshots", "P1", {"social_account_id": ref("social_accounts", True), "content_post_id": ref("content_posts", True), "metric_definition_id": ref("metric_definitions"), "value_numeric": f("numeric", True), "value_json": f("jsonb", True), "missing_reason": f(nullable=True, enum="not_supported|insufficient_audience|not_collected|provider_delay|permission_missing|deleted|unknown"), "observed_at": f("timestamptz"), "metric_as_of": f("timestamptz", True), "period_start": f("timestamptz", True), "period_end": f("timestamptz", True), "provider_request_id": f(nullable=True), "collection_job_id": ref("async_jobs", True), "source_type": f(enum="provider_api|customer_import|customer_manual"), "completeness": f(enum="complete_by_provider|provisional|unknown"), "raw_payload_hash": f(nullable=True)}, immutable=True, retention="provider_specific", checks=["exactly one of social_account_id/content_post_id", "numeric and JSON values cannot both be populated", "missing value requires reason; true zero has a numeric value", "metric_as_of is null if provider does not supply an interpretable as-of timestamp"])
t("feature_definitions", "P3", {"name": f(), "version": f(), "value_type": f(), "transformation_code_hash": f(), "allowed_decision_stage": f(enum="prepublication|postpublication_analysis"), "purpose": f(), "missing_value_policy": f(), "lineage_requirement": f()}, scope="catalog", immutable=True, unique=[["name", "version"]], retention="definition_catalog")
t("feature_values", "P3", {"social_account_id": ref("social_accounts", True), "content_post_id": ref("content_posts", True), "candidate_id": ref("recommendation_candidates", True), "feature_definition_id": ref("feature_definitions"), "value": f("jsonb", True), "missing_reason": f(nullable=True), "event_time": f("timestamptz", True), "available_at": f("timestamptz"), "decision_at": f("timestamptz"), "source_snapshot_ids": f("uuid[]", note="All IDs must resolve in tenant; enforced in materialization validation"), "source_item_ids": f("uuid[]"), "lineage_digest": f()}, immutable=True, retention="derived_from_sources", checks=["exactly one target among account/post/candidate", "prepublication feature availability and all lineage availability <= decision_at"])
t("label_annotations", "P1", {"content_post_id": ref("content_posts", True), "candidate_id": ref("recommendation_candidates", True), "artifact_version_id": ref("artifact_versions", True), "taxonomy_version": f(), "label_key": f(), "label_value": f("jsonb"), "annotator_type": f(enum="human|llm|rule"), "annotator_user_id": ref("users", True), "model_run_id": ref("model_runs", True), "confidence": f("numeric", True), "annotated_at": f("timestamptz"), "outcome_blinded": f("boolean"), "supersedes_id": ref("label_annotations", True)}, immutable=True, retention="derived_from_sources", checks=["exactly one annotation target", "AI tags are not outcome labels or ground truth"])
t("outcome_labels", "P3", {"content_post_id": ref("content_posts"), "metric_definition_id": ref("metric_definitions"), "horizon_seconds": f("integer"), "intended_cutoff_at": f("timestamptz"), "actual_as_of": f("timestamptz", True), "observation_tolerance_seconds": f("integer"), "snapshot_id": ref("metric_snapshots", True), "value": f("numeric", True), "status": f(enum="mature|immature|delayed|horizon_unobserved|deleted|permission_lost|unsupported|invalid"), "eligible_at": f("timestamptz", True), "definition_version": f(), "revision": f("integer"), "exclusion_reason": f(nullable=True)}, immutable=True, unique=[["tenant_id", "content_post_id", "metric_definition_id", "horizon_seconds", "definition_version", "revision"]], retention="derived_from_sources", checks=["9-day cumulative observation cannot be relabeled 7-day without valid provider window", "unpublished/immature/missing is never silently encoded as zero"])

t("brief_options", "P0", {"brand_id": ref("brands"), "goal_id": ref("goals"), "brief_group_key": f(), "candidate_index": f("integer"), "proposal": f("jsonb", note="Customer-material topic, angle, source references and production effort; no invented account analysis"), "source_item_ids": f("uuid[]"), "proposal_digest": f(), "selected_by": ref("users", True), "selected_at": f("timestamptz", True), "selection_state": f(enum="offered|selected|dismissed|superseded")}, unique=[["tenant_id", "brief_group_key", "candidate_index"]], checks=["same group belongs to one authorized brand/goal", "no unsupported growth prediction; label as customer-material curation"], note="R1 minimal three-candidate flow before formal account analytics, exposure experimentation or ML.")

t("recommendations", "P1", {"brand_id": ref("brands"), "goal_id": ref("goals"), "social_account_id": ref("social_accounts", True), "decision_at": f("timestamptz"), "policy_version": f(), "mode": f(enum="editorial_rules|own_history_baseline|validated_model|experiment"), "model_run_id": ref("model_runs", True), "input_digest": f(), "eligible_set_digest": f(), "data_coverage": f("jsonb"), "evidence_summary": f("jsonb")}, immutable=True)
t("recommendation_candidates", "P1", {"recommendation_id": ref("recommendations"), "candidate_key": f(), "proposal": f("jsonb", note="topic, angle, hook, format, effort, sources, hypothesis"), "source_item_ids": f("uuid[]"), "artifact_version_id": ref("artifact_versions", True), "score": f("numeric", True), "score_semantics": f(enum="none|editorial_priority|rank_score|count_prediction|calibrated_probability"), "score_target_definition": f(nullable=True), "rank": f("integer"), "eligible": f("boolean"), "ineligibility_reason": f(nullable=True)}, immutable=True, unique=[["tenant_id", "recommendation_id", "candidate_key"]], checks=["rank score never labeled probability; source rights checked for each permitted purpose"])
t("experiments", "P3", {"brand_id": ref("brands", True), "protocol_version": f(), "unit": f(enum="brand|account|decision"), "arms": f("jsonb"), "primary_outcome": f("jsonb"), "eligibility_rule": f(), "start_at": f("timestamptz"), "stop_at": f("timestamptz", True), "status": f(enum="draft|running|stopped|analyzed"), "safety_rules": f("jsonb"), "analysis_plan_hash": f()}, note="Tenant-scoped instance; any multi-tenant experiment requires separate permitted governance and no raw customer-data pooling.")
t("experiment_assignments", "P3", {"experiment_id": ref("experiments"), "brand_id": ref("brands", True), "social_account_id": ref("social_accounts", True), "recommendation_id": ref("recommendations", True), "unit_key": f(), "arm": f(), "probability": f("numeric"), "assigned_at": f("timestamptz"), "randomization_version": f()}, immutable=True, unique=[["tenant_id", "experiment_id", "unit_key"]], checks=["0 < probability <= 1; allocation fixed according to preregistered unit"])
t("recommendation_exposures", "P1", {"recommendation_id": ref("recommendations"), "candidate_id": ref("recommendation_candidates"), "viewer_user_id": ref("users"), "client_event_id": f(), "session_ref": f(), "position": f("integer"), "rendered_at": f("timestamptz"), "viewable_at": f("timestamptz", True), "assignment_id": ref("experiment_assignments", True), "logging_policy_version": f(), "propensity": f("numeric", True), "propensity_semantics": f(nullable=True, enum="action_probability|slate_probability|position_probability"), "probability_source": f(enum="known_randomization|unknown"), "eligible_set_digest": f()}, immutable=True, unique=[["tenant_id", "client_event_id"]], retention="behavior_events", checks=["propensity null unless known from logging policy; model score is not propensity", "candidate belongs to recommendation", "candidate generation does not imply exposure"])
t("recommendation_feedback", "P1", {"recommendation_id": ref("recommendations"), "candidate_id": ref("recommendation_candidates", True), "exposure_id": ref("recommendation_exposures", True), "actor_user_id": ref("users"), "event": f(enum="selected|dismissed|edited|production_started|production_completed|published|explicit_feedback"), "event_at": f("timestamptz"), "artifact_version_id": ref("artifact_versions", True), "content_post_id": ref("content_posts", True), "source": f(enum="first_party_workflow|provider_api|customer_report"), "detail": f("jsonb")}, immutable=True, retention="behavior_events")

t("dataset_manifests", "P3", {"purpose": f(enum="own_account_model|licensed_reference_model|evaluation"), "dataset_version": f(), "source_policy_digest": f(), "feature_schema_version": f(), "target_definition": f("jsonb"), "cutoff_at": f("timestamptz"), "split_manifest_object_key": f(), "split_manifest_hash": f(), "snapshot_object_key": f(), "snapshot_hash": f(), "rights_check_at": f("timestamptz"), "status": f(enum="draft|rights_validated|frozen|invalidated|deleted"), "coverage_report": f("jsonb"), "expires_at": f("timestamptz", True)}, retention="training_snapshot", checks=["no cross-client Meta data pooling; opt-in alone is insufficient", "frozen snapshot remains subject to revocation/deletion; retention is not perpetual"])
t("dataset_members", "P3", {"dataset_id": ref("dataset_manifests"), "content_post_id": ref("content_posts", True), "source_item_id": ref("source_items", True), "outcome_label_id": ref("outcome_labels", True), "rights_grant_id": ref("rights_grants"), "feature_row_hash": f(), "decision_at": f("timestamptz"), "label_available_at": f("timestamptz", True), "split_role": f(enum="train|validation|calibration|test"), "fold_id": f(), "account_group": f(), "campaign_duplicate_group": f(nullable=True), "included": f("boolean"), "exclusion_reason": f(nullable=True)}, immutable=True, retention="derived_from_sources", checks=["all customer resources within dataset tenant; separate licensed-reference workspace may contain only independently permitted assets", "every member must pass purpose/provider clearance at assembly and before training"])
t("model_versions", "P3", {"dataset_id": ref("dataset_manifests"), "model_family": f(enum="rules|account_baseline|ridge|elastic_net|glm|mixed_effects|xgboost_regressor|xgboost_ranker|other"), "model_version": f(), "code_commit": f(), "environment_digest": f(), "hyperparameters": f("jsonb"), "random_seed": f("integer"), "artifact_object_key": f(), "artifact_hash": f(), "evaluation_report_key": f(), "metrics": f("jsonb"), "approved_use": f(), "status": f(enum="candidate|shadow|approved|retired|blocked_rights|deleted"), "approved_by": ref("users", True)}, immutable=True, retention="model_lineage", note="Metadata initially append-only; deployment status changes recorded by a successor release/event, not alteration of evaluation history.")
t("model_deployments", "P3", {"model_version_id": ref("model_versions"), "serving_scope": f(enum="own_account|permitted_licensed_reference"), "mode": f(enum="shadow|active|retired|blocked_rights"), "activated_at": f("timestamptz", True), "deactivated_at": f("timestamptz", True), "decision_reason": f(), "approved_by": ref("users")}, retention="model_lineage", checks=["serving enabled only if current rights and release evaluation permit", "no implicit permission to transfer a customer-trained model across tenants"])
t("model_runs", "P0", {"brand_id": ref("brands"), "async_job_id": ref("async_jobs", True), "kind": f(enum="generation|annotation|baseline|prediction|training|evaluation"), "model_version_id": ref("model_versions", True), "provider_model": f(nullable=True), "workflow_version": f(nullable=True), "prompt_version": f(nullable=True), "input_schema_version": f(), "input_digest": f(), "feature_cutoff_at": f("timestamptz", True), "status": f(enum="queued|running|succeeded|failed|cancelled|unknown"), "started_at": f("timestamptz", True), "completed_at": f("timestamptz", True), "output_digest": f(nullable=True), "error_code": f(nullable=True)}, retention="run_metadata")

t("artifacts", "P0", {"brand_id": ref("brands"), "kind": f(enum="carousel|caption|video_project|script|report"), "title": f(), "status": f(enum="draft|in_review|approved|exported|archived|deleted"), "created_by": ref("users"), "latest_version_id": ref("artifact_versions", True)})
t("artifact_versions", "P0", {"artifact_id": ref("artifacts"), "version": f("integer"), "parent_version_id": ref("artifact_versions", True), "brand_profile_version_id": ref("brand_profile_versions"), "goal_id": ref("goals"), "brief_option_id": ref("brief_options", True), "created_by": ref("users"), "model_run_id": ref("model_runs", True), "template_key": f(), "template_version": f(), "schema_version": f(), "content": f("jsonb", note="Validated carousel/video_project/caption schema; complete immutable state"), "caption": f(nullable=True), "source_item_ids": f("uuid[]"), "digest": f(), "change_summary": f("jsonb")}, immutable=True, unique=[["tenant_id", "artifact_id", "version"]], checks=["parent belongs to same artifact", "brand_profile/goal/source resources must be authorized for artifact brand", "any edit creates a new version"])
t("artifact_files", "P0", {"artifact_version_id": ref("artifact_versions"), "role": f(enum="preview|export|source|thumbnail|subtitle"), "private_object_key": f(), "mime_type": f(), "byte_size": f("bigint"), "checksum": f(), "width": f("integer", True), "height": f("integer", True), "duration_ms": f("integer", True), "page_index": f("integer", True), "delete_due_at": f("timestamptz", True)}, immutable=True, retention="artifact_files")
t("approval_versions", "P0", {"artifact_version_id": ref("artifact_versions"), "reviewer_user_id": ref("users"), "target_social_account_id": ref("social_accounts", True), "purpose": f(enum="export|publish"), "decision": f(enum="approved|rejected|revoked"), "decision_at": f("timestamptz"), "approved_payload_digest": f(), "publication_options": f("jsonb"), "schedule_policy": f("jsonb"), "note": f(nullable=True), "supersedes_id": ref("approval_versions", True)}, immutable=True, checks=["publish requires target account; approved digest includes version, caption, assets, target and public options", "revocation invalidates pending use; original decision remains audit evidence"])

t("async_jobs", "P0", {"brand_id": ref("brands", True), "requested_by": ref("users"), "job_type": f(), "payload_schema_version": f(), "payload": f("jsonb", note="Permitted resource references only; no raw OAuth token"), "idempotency_key": f(), "request_digest": f(), "status": f(enum="queued|leased|running|succeeded|failed_retryable|failed_final|cancelled|unknown"), "attempt_count": f("integer"), "next_attempt_at": f("timestamptz", True), "lease_owner": f(nullable=True), "lease_expires_at": f("timestamptz", True), "cancelled_at": f("timestamptz", True), "result_ref": f("jsonb", True), "last_error_code": f(nullable=True)}, unique=[["tenant_id", "job_type", "idempotency_key"]], retention="run_metadata", checks=["same idempotency key with different request digest => 409", "lease expiry does not imply external effect failed"])
t("outbox_events", "P0", {"brand_id": ref("brands", True), "event_type": f(), "schema_version": f(), "run_id": ref("async_jobs", True), "artifact_version_id": ref("artifact_versions", True), "payload": f("jsonb"), "payload_digest": f(), "occurred_at": f("timestamptz"), "destination": f(enum="internal|rita"), "status": f(enum="pending|delivering|delivered|dead_letter"), "attempt_count": f("integer"), "next_attempt_at": f("timestamptz", True)}, retention="event_metadata", checks=["state mutation and outbox insert in same transaction", "external callback payload purpose/minimization check before transmission"])
t("publishing_jobs", "P2", {"brand_id": ref("brands"), "async_job_id": ref("async_jobs"), "social_account_id": ref("social_accounts"), "artifact_version_id": ref("artifact_versions"), "approval_version_id": ref("approval_versions"), "payload_digest": f(), "scheduled_at": f("timestamptz"), "idempotency_key": f(), "state": f(enum="queued|preflight|container_created|processing|publish_requested|published|failed_retryable|failed_final|unknown|cancelled"), "external_container_id": f(nullable=True), "external_post_id": f(nullable=True), "content_post_id": ref("content_posts", True), "last_reconciled_at": f("timestamptz", True), "reconciliation_result": f(nullable=True), "confirmed_at": f("timestamptz", True)}, unique=[["tenant_id", "idempotency_key"], ["tenant_id", "social_account_id", "external_post_id"]], checks=["all account/artifact/approval brands agree", "preflight repeated immediately before external effect", "unknown forbids blind republish; reconcile or explicit reviewed resolution"])
t("publishing_attempts", "P2", {"publishing_job_id": ref("publishing_jobs"), "attempt_number": f("integer"), "operation": f(enum="create_container|check_container|publish|reconcile|cancel"), "request_digest": f(), "requested_at": f("timestamptz"), "responded_at": f("timestamptz", True), "provider_request_id": f(nullable=True), "result": f(enum="success|retryable_error|final_error|timeout_unknown"), "safe_error_code": f(nullable=True), "retry_after_at": f("timestamptz", True), "response_digest": f(nullable=True)}, immutable=True, unique=[["tenant_id", "publishing_job_id", "attempt_number"]], retention="run_metadata")
t("usage_reservations", "P0", {"async_job_id": ref("async_jobs"), "meter": f(), "currency": f(), "reserved_units": f("numeric"), "reserved_cost_minor": f("bigint"), "status": f(enum="reserved|provisional|settled|released"), "expires_at": f("timestamptz"), "budget_policy_version": f()}, unique=[["tenant_id", "async_job_id", "meter"]], retention="billing_minimum", checks=["reservation and available budget atomically updated", "expiry does not erase potentially incurred provider cost"])
t("usage_ledger", "P0", {"async_job_id": ref("async_jobs", True), "model_run_id": ref("model_runs", True), "reservation_id": ref("usage_reservations", True), "event_key": f(), "entry_type": f(enum="provider_cost|customer_usage|customer_refund|cost_adjustment"), "meter": f(), "quantity": f("numeric"), "cost_minor": f("bigint"), "currency": f(), "price_version": f(), "cost_status": f(enum="actual|estimated|provisional"), "occurred_at": f("timestamptz"), "usage_context": f(enum="paid|trial|internal_test|classroom")}, immutable=True, unique=[["tenant_id", "event_key"]], retention="billing_minimum")
t("billing_events", "P0", {"provider": f(), "external_event_id": f(), "kind": f(enum="subscription|invoice|payment|refund|marketplace_fee|supplier_settlement"), "amount_minor": f("bigint"), "currency": f(), "occurred_at": f("timestamptz"), "safe_reference": f(), "verified_signature": f("boolean"), "related_run_id": ref("async_jobs", True)}, immutable=True, unique=[["tenant_id", "provider", "external_event_id"]], retention="billing_minimum", checks=["product subscription, Rita marketplace fee and supplier settlement are distinct entries"])
t("audit_events", "P0", {"actor_user_id": ref("users", True), "actor_type": f(enum="user|worker|operator|integration"), "brand_id": ref("brands", True), "action": f(), "resource_type": f(), "resource_id": f("uuid", True), "result": f(enum="allowed|denied|failed"), "reason_code": f(nullable=True), "request_correlation_id": f(), "occurred_at": f("timestamptz"), "safe_metadata": f("jsonb")}, immutable=True, retention="audit_minimum", checks=["no tokens, raw prompts, customer content or private media in ordinary logs"])
t("integration_subjects", "P1", {"integration": f(enum="rita"), "issuer": f(), "external_subject": f(), "external_organization": f(nullable=True), "local_user_id": ref("users"), "membership_id": ref("memberships"), "allowed_modules": f("text[]"), "status": f(enum="active|revoked"), "last_exchange_at": f("timestamptz", True)}, unique=[["tenant_id", "issuer", "external_subject"]], retention="identity", checks=["external organization string never grants local membership automatically", "local membership must belong to mapped local user"])

# Materialize explicit FK column pairs, including tenant boundary.
by_name = {x["name"]: x for x in tables}
for table in tables:
    fks = []
    for name, field in table["columns"].items():
        field["introduced_in_phase"] = table["phase"]
        target = field.pop("references", None)
        if not target:
            continue
        target_scope = by_name[target]["scope"]
        tenant_join = target_scope == "tenant"
        assert not tenant_join or table["scope"] == "tenant"
        introduced = max(table["phase"], by_name[target]["phase"])
        field["introduced_in_phase"] = introduced
        fks.append({
            "columns": ["tenant_id", name] if tenant_join else [name],
            "references": {"table": target, "columns": ["tenant_id", "id"] if tenant_join else ["id"]},
            "on_delete": "RESTRICT; deletion workflow applies explicit order or tombstone minimization",
            "introduced_in_phase": introduced,
        })
    table["foreign_keys"] = fks


def api(method, path, phase, permission, request, response, errors, **extra):
    return {"method": method, "path": path, "phase": phase, "permission": permission, "request": request, "success": response, "error_codes": errors, **extra}


apis = [
    api("POST", "/v1/brands", "P0", "tenant.manage_brand", {"name": "string", "timezone": "IANA string"}, {"status": 201, "brand_id": "uuid"}, ["FORBIDDEN", "PLAN_LIMIT"]),
    api("POST", "/v1/brands/{brand_id}/brief-options", "P0", "brand.draft", {"goal_id": "uuid", "source_item_ids": ["uuid"], "candidate_count": 3}, {"status": 202, "run_id": "uuid", "source_type": "customer_material_curation", "account_analytics": False}, ["RIGHTS_NOT_ALLOWED", "BUDGET_EXCEEDED"], required_headers=["Idempotency-Key"]),
    api("POST", "/v1/brief-options/{option_id}/select", "P0", "brand.draft", {"seen_proposal_digest": "sha256"}, {"status": 200, "selected_option_id": "uuid", "draft_prefill": "authorized source/goal/selected proposal references"}, ["DIGEST_MISMATCH", "NOT_FOUND_OR_FORBIDDEN"]),
    api("POST", "/v1/brands/{brand_id}/drafts", "P0", "brand.draft", {"goal_id": "uuid", "brand_profile_version_id": "uuid", "source_item_ids": ["uuid"], "template_key": "string", "card_count": "6|8", "budget_limit_minor": "integer"}, {"status": 202, "run_id": "uuid", "status_url": "/v1/runs/{run_id}"}, ["RIGHTS_NOT_ALLOWED", "BUDGET_EXCEEDED", "INVALID_SOURCE", "IDEMPOTENCY_CONFLICT"], required_headers=["Idempotency-Key"]),
    api("POST", "/v1/artifacts/{artifact_id}/versions", "P0", "brand.edit", {"base_version_id": "uuid", "patches": [{"path": "/cards/2/body", "value": "updated text"}], "mode": "manual"}, {"status": 201, "version_id": "uuid", "digest": "sha256", "approval_status": "not_approved", "render_run_id": "uuid"}, ["VERSION_CONFLICT", "SCHEMA_INVALID", "RIGHTS_NOT_ALLOWED", "BUDGET_EXCEEDED"], concurrency="If-Match digest or base_version_id; no overwrite of a changed base", billing="manual text edits no AI meter; rendering allowance follows explicit plan"),
    api("POST", "/v1/artifact-versions/{version_id}/ai-revisions", "P0", "brand.edit", {"base_digest": "sha256", "allowed_fields": ["cards.2.body"], "instruction": "shorten selected body", "budget_limit_minor": "integer"}, {"status": 202, "run_id": "uuid"}, ["VERSION_CONFLICT", "RIGHTS_NOT_ALLOWED", "BUDGET_EXCEEDED", "INVALID_EDIT_SCOPE"], required_headers=["Idempotency-Key"], note="Async model output can change only permitted fields; success creates a new unapproved version and preview, never overwrites the approved base."),
    api("POST", "/v1/artifact-versions/{version_id}/approvals", "P0", "brand.review", {"decision": "approved|rejected", "purpose": "export|publish", "seen_digest": "sha256", "target_social_account_id": "uuid|null", "publication_options": {}, "schedule_policy": {}}, {"status": 201, "approval_id": "uuid", "approved_payload_digest": "sha256"}, ["DIGEST_MISMATCH", "FORBIDDEN", "TARGET_ACCOUNT_MISMATCH"]),
    api("POST", "/v1/artifact-versions/{version_id}/exports", "P0", "brand.view", {"format": "png_zip|jpeg_zip|caption_txt|project_json"}, {"status": 202, "run_id": "uuid"}, ["RIGHTS_NOT_ALLOWED", "RENDER_INVALID"]),
    api("GET", "/v1/files/{file_id}/access", "P0", "brand.view + current resource access", {}, {"status": 200, "url": "short-lived signed URL", "expires_at": "ISO8601"}, ["NOT_FOUND_OR_FORBIDDEN", "RESOURCE_DELETED"], note="Signed URL is issued only after auth; no permanent public object path."),
    api("POST", "/v1/brands/{brand_id}/connections/instagram/start", "P1", "brand.connect", {"capability": "insights|publishing"}, {"status": 200, "authorization_url": "provider OAuth URL", "state_expires_at": "ISO8601"}, ["PROVIDER_ACCESS_NOT_APPROVED", "FORBIDDEN"], note="Store one-use state bound to session/tenant/brand; use supported OAuth protections. Never return access tokens."),
    api("GET", "/v1/connections/instagram/callback", "P1", "one-use validated OAuth state and authenticated linkage", {"code": "provider authorization code", "state": "unpredictable state"}, {"status": 303, "location": "same-origin connection status page"}, ["OAUTH_STATE_INVALID", "ACCOUNT_TYPE_UNSUPPORTED", "SCOPE_MISSING", "EXCHANGE_FAILED"], note="Server-side exchange; exact redirect allowlist; token in vault. Log redaction required."),
    api("DELETE", "/v1/connections/{connection_id}", "P1", "brand.connect", {}, {"status": 202, "state": "revoked_locally", "deletion_request_id": "uuid"}, ["NOT_FOUND_OR_FORBIDDEN"], side_effect="Immediately stop local access/jobs, delete vault material and process provider revocation/deletion obligations."),
    api("POST", "/v1/accounts/{account_id}/sync", "P1", "brand.analyze", {"window": "supported recent window", "metric_set": "basic_v1"}, {"status": 202, "run_id": "uuid", "source_type": "provider_api"}, ["CONNECTION_REVOKED", "QUOTA_DEFERRED", "SCOPE_MISSING", "UNSUPPORTED_METRIC_SET"], required_headers=["Idempotency-Key"]),
    api("POST", "/v1/brands/{brand_id}/metric-imports", "P1", "brand.analyze", {"source_file_id": "uuid", "extracted_at": "ISO8601", "mapping_version": "string", "customer_rights_confirmation": "reference"}, {"status": 202, "run_id": "uuid", "source_type": "customer_import", "api_connection": False}, ["IMPORT_SCHEMA_INVALID", "RIGHTS_NOT_ALLOWED"], note="Manual import is not described as official API integration or live analytics."),
    api("GET", "/v1/accounts/{account_id}/diagnosis", "P1", "brand.analyze", {"as_of": "ISO8601|null", "goal_id": "uuid"}, {"status": 200, "observations": [], "baseline_definition": {}, "missingness": {}, "hypotheses": [], "source_type": "provider_api|customer_import", "last_collected_at": "ISO8601|null"}, ["NOT_FOUND_OR_FORBIDDEN"], note="No algorithm-cause or guaranteed growth claim."),
    api("POST", "/v1/brands/{brand_id}/recommendations", "P1", "brand.draft", {"goal_id": "uuid", "account_id": "uuid|null", "constraints": {"format": "carousel|reel", "production_minutes": 60}}, {"status": 202, "run_id": "uuid"}, ["RIGHTS_NOT_ALLOWED", "BUDGET_EXCEEDED"], required_headers=["Idempotency-Key"], fallback="Editorial rules and permitted own-history baseline; label absence of account evidence."),
    api("POST", "/v1/recommendation-exposures", "P1", "brand.view", {"recommendation_id": "uuid", "candidate_id": "uuid", "client_event_id": "uuid", "position": 1, "rendered_at": "ISO8601", "viewable_at": "ISO8601|null"}, {"status": 202, "exposure_id": "uuid", "duplicate": False}, ["INVALID_CANDIDATE", "FORBIDDEN"], note="Server joins policy/assignment/known propensity; client cannot invent probability."),
    api("POST", "/v1/publishing-jobs", "P2", "brand.publish + valid provider scope + approval", {"artifact_version_id": "uuid", "approval_version_id": "uuid", "social_account_id": "uuid", "payload_digest": "sha256", "scheduled_at": "ISO8601"}, {"status": 202, "publishing_job_id": "uuid", "state": "queued"}, ["APPROVAL_REQUIRED", "APPROVAL_REVOKED", "DIGEST_MISMATCH", "CONNECTION_REVOKED", "RIGHTS_NOT_ALLOWED", "IDEMPOTENCY_CONFLICT"], required_headers=["Idempotency-Key"], side_effect="External publication only after execution-time preflight."),
    api("POST", "/v1/publishing-jobs/{job_id}/reconcile", "P2", "brand.publish or audited operator", {}, {"status": 202, "state": "reconciliation_queued"}, ["NOT_FOUND_OR_FORBIDDEN"], note="Reconciliation is a read/check task; it is not permission to republish an unknown request."),
    api("GET", "/v1/runs/{run_id}", "P0", "brand access to run", {}, {"status": 200, "run_id": "uuid", "state": "queued|running|succeeded|failed|unknown|cancelled", "artifact_refs": [], "usage": {"status": "actual|provisional", "customer_units": 1}, "error": None}, ["NOT_FOUND_OR_FORBIDDEN"]),
    api("POST", "/v1/deletion-requests", "P0", "scope-specific owner authority", {"scope": "brand|tenant|connection|source|artifact|model_purpose", "resource_id": "uuid|null"}, {"status": 202, "deletion_request_id": "uuid", "online_access": "blocked", "retention_exceptions": []}, ["FORBIDDEN", "INVALID_SCOPE"], note="Legal minimum metadata and backup expiry disclosed separately; do not promise immediate model unlearning."),
]

rita = {
    "status": "PROPOSED_NOT_VERIFIED_AS_EXISTING_RITA_API",
    "exchange": {"method": "POST", "path": "/v1/integrations/rita/exchange", "input": {"one_time_code": "opaque string", "expected_audience": "configured service id"}, "verification": ["configured issuer/audience", "expiry", "nonce/jti replay prevention", "server-to-server exchange", "explicit existing local membership mapping"], "output": {"session_handle": "opaque limited-scope handle", "allowed_modules": ["draft_carousel"]}},
    "module_manifest": {"module_key": "draft_carousel", "version": "1.0.0-proposed", "input_schema": "DraftCarouselInput.v1", "output_schema": "ArtifactRef.v1", "side_effect": "private_artifact_only", "required_permission": "brand.draft", "required_data_purpose": "process_for_user", "budget_policy": "server_enforced", "oauth_tokens_in_input": False},
    "run_request": {"method": "POST", "path": "/v1/runs", "required_header": "Idempotency-Key", "input": {"module_key": "draft_carousel", "module_version": "1.0.0-proposed", "brand_id": "authorized-local-uuid", "input": {"goal_id": "uuid", "source_item_ids": ["uuid"]}, "budget_limit_minor": 1000, "currency": "KRW"}, "note": "1000 is payload syntax example, not price quote; server applies current plan limits."},
    "event_example": {"event_id": "uuid", "schema_version": "1", "event_type": "artifact.approved", "occurred_at": "2026-09-29T00:00:00Z", "integration_tenant_ref": "opaque mapped reference", "run_id": "uuid", "artifact_id": "uuid", "artifact_version_id": "uuid", "artifact_digest": "sha256", "evidence_source": "first_party_workflow", "permission_purpose": "permitted_execution_metadata", "usage": {"status": "actual", "meter": "carousel_set", "quantity": 1}},
    "callback_verification": ["signature over timestamp + event_id + body digest with managed rotating key", "bounded timestamp tolerance", "event_id deduplication", "retry with backoff and dead letter", "purpose and minimization check", "no OAuth token/raw customer media/full prompt in default event"],
    "billing_separation": ["internal_provider_cost", "content_service_subscription", "Rita_marketplace_fee", "supplier_settlement"],
    "not_implied_by_callback": ["independent artifact quality verification", "actual social publication", "verified views or business revenue", "permission to publish"],
}

contract = {
    "document_kind": "architecture_review_contract_proposal",
    "version": "0.1.0",
    "written_at": "2026-09-29",
    "implemented": False,
    "limitations": ["Not executable SQL migrations or a complete OpenAPI document", "No existing application changed", "No account connected or data fetched with customer credentials", "No cross-client Meta training permission asserted", "Phase labels do not promise all phases within 8 weeks"],
    "phases": {"P0": "narrow direct-use carousel workflow", "P1": "approved readonly account analytics and rule/baseline curation", "P2": "bounded video editing and separately approved publishing", "P3": "rights-cleared optional ML and controlled recommendation experiments"},
    "release_plan_precedence": "Final masterplan section 07 R0/R1/R2 release definitions govern budget and schedule. P0/P1/P2/P3 are technical expansion levels, not release dates. R1 includes P0 brief_options (three customer-material proposals), 72 student hours, 24-40 expert developer hours, 6-8 designer hours, 12-16 measurement expert hours, total KRW 4.68-6.50m planning assumption.",
    "global_conventions": {
        "timestamps": "UTC timestamptz; display timezone separately",
        "tenant_resolution": "authenticated membership; request tenant selector is untrusted",
        "ids": "UUID; no authority inferred from possession of an ID",
        "rls": "tenant + brand grants; application DB role is neither table owner nor superuser/BYPASSRLS; transaction-scoped tenant context",
        "tenant_foreign_keys": "(tenant_id, resource_id) -> (tenant_id, id); brand consistency requires explicit service/DB constraints too",
        "global_catalogs": "definitions only, no customer content; restricted control identities never exposed as customer directory",
        "deletion": "RESTRICT by default; explicit dependency-aware deletion or minimal tombstone, content is not retained merely to keep FK alive",
        "append_only": "business history immutable while retained; lawful deletion/purpose revocation can purge content and append audit evidence",
        "logical_checks": "check_contracts requiring cross-table checks are service/constraint-trigger invariants, not literal SQL CHECK expressions",
        "phase_migrations": "Columns and FKs referencing later-phase tables are introduced only at their introduced_in_phase; P0 is not a mandate to build all tables. Build schema migrations in dependency-aware stages.",
        "error_envelope": {"code": "stable uppercase enum", "message": "safe localized text", "retryable": False, "correlation_id": "uuid", "retry_after": None},
        "idempotency": "tenant+operation+key unique; request digest conflict returns 409; provider external effects still require reconciliation",
        "permissions": "roles are defaults, brand action grants and current provider capability are enforced at request and job execution",
        "purpose_registry": ["process_for_user", "benchmark", "train", "reuse_media", "publish"],
        "meta_default": "customer-directed own-account permitted processing only; cross-client training and benchmarking denied absent separately verified authorization",
    },
    "retention_policies": {
        "customer_workspace": "Contract-specific active use; immediate access block upon valid deletion; online deletion SLA and backup expiry must be finalized before launch",
        "identity": "Minimum needed for active membership and applicable legal evidence; no global customer directory",
        "consent_evidence": "Minimum proof with no unnecessary source content; reviewed legal retention",
        "rights_evidence": "Purpose/provider/license evidence while necessary; revocation affects future processing immediately",
        "deletion_evidence": "Minimal deletion status and lawful exceptions; no original content",
        "connection": "Token disabled and vault secret removed at disconnect; provider revocation attempted and logged",
        "source_specific": "Provider/license-specific refresh and deletion; no default indefinite retention",
        "provider_specific": "Current provider terms, consent and measured need; expiry enforced by adapters",
        "definition_catalog": "Versioned noncustomer definitions retained for interpretation",
        "derived_from_sources": "Cannot outlive applicable purpose/rights without independently valid basis; lineage deletion propagates",
        "behavior_events": "Minimum duration to evaluate stated customer workflow; cross-client sharing/training is not automatic",
        "training_snapshot": "Frozen reproducibility snapshot with explicit expiry and revocation; no automatic data pooling",
        "model_lineage": "Track affected releases; purge/retrain/disable according to valid obligations, no instant unlearning promise",
        "artifact_files": "Private storage; object deletion follows parent and license obligations; temporary publication URLs expire",
        "run_metadata": "Minimal operational metadata; ordinary diagnostic logs proposed 30 days pending policy review",
        "event_metadata": "Minimal permitted delivery evidence with bounded retention; no raw prompts or tokens",
        "billing_minimum": "Applicable legal/accounting period to be determined; content source deleted separately",
        "audit_minimum": "Purpose-limited security evidence; retention set before launch; no private content or tokens",
    },
    "tables": tables,
    "artifact_content_examples": {
        "carousel_v1": {"schema_version": "carousel.v1", "template_key": "original_educational_v1", "brand_colors": ["#24364B", "#FAF8F3"], "cards": [{"key": "card_1", "role": "cover", "headline": "고객이 수정하는 제목", "body": "직접 수정 가능한 본문", "source_item_ids": [], "photo_source_item_id": None}], "caption": "편집 가능한 캡션", "layout_constraints": {"allowed_card_counts": [6, 8], "text_overflow": "block_export_until_resolved"}},
        "video_project_v1_future": {"schema_version": "video.v1", "format": "9:16", "clips": [{"source_item_id": "uuid", "in_ms": 0, "out_ms": 5000, "crop": "center"}], "subtitles": [{"start_ms": 0, "end_ms": 3000, "text": "수정 가능한 자막"}], "music_source_item_id": None, "rights_required": ["process_for_user", "reuse_media", "publish_when_enabled"]},
    },
    "apis": apis,
    "rita": rita,
    "critical_invariant_ids": [f"I{i:02d}" for i in range(1, 11)],
    "acceptance_test_ids": [f"E{i:02d}" for i in range(1, 13)],
    "source_document": "architecture_ml.md",
}

# Contract consistency checks; these are not production application tests.
assert len(by_name) == len(tables)
for table in tables:
    assert table["retention_policy"] in contract["retention_policies"]
    assert all(c in table["columns"] for c in table["primary_key"])
    for unique in table["unique_constraints"]:
        assert all(c in table["columns"] for c in unique), (table["name"], unique)
    for fk in table["foreign_keys"]:
        target = by_name[fk["references"]["table"]]
        assert all(c in table["columns"] for c in fk["columns"])
        assert all(c in target["columns"] for c in fk["references"]["columns"])
        assert len(fk["columns"]) == len(fk["references"]["columns"])
        if target["scope"] == "tenant":
            assert fk["columns"][0] == "tenant_id"
assert len({(x["method"], x["path"]) for x in apis}) == len(apis)
OUT.write_text(json.dumps(contract, ensure_ascii=False, indent=2) + "\n")
json.loads(OUT.read_text())
print(json.dumps({"path": str(OUT), "tables": len(tables), "apis": len(apis), "foreign_keys": sum(len(t["foreign_keys"]) for t in tables), "status": "proposal JSON validated"}))
