import{productMode}from'@/lib/cora/release';
import{NextRequest}from'next/server';import{json,user,sameOrigin,body}from'@/lib/cora/http';import{store}from'@/lib/cora/store';import{generateText}from'@/lib/cora/gateway';import{validateDraft}from'@/lib/cora/model';import{randomUUID}from'node:crypto';import{knowledgeContext}from'@/lib/cora/platform/knowledge';
export const runtime='nodejs';export const maxDuration=180;
export async function POST(req:NextRequest){if(!sameOrigin(req))return json({error:'허용되지 않은 요청입니다.'},403);const u=user(req);if(!u)return json({error:'로그인이 필요합니다.'},401);
 try{const b=await body(req);const base=validateDraft(b.draft);const client=base.clientId?store().accessibleClient(u.id,base.clientId):null;if(base.clientId&&!client)return json({error:'고객사를 찾을 수 없습니다.'},404);const clientContext=client?[client.voice,client.pillars,client.avoid].filter(Boolean).join('\n').slice(0,4000):'';if(b.instructions!==undefined&&(typeof b.instructions!=='string'||b.instructions.length>2000))throw new Error('브랜드 지시는 2000자 이내입니다.');if(store().generationCount(u.id)>=10)return json({error:'하루 10회 로컬 생성 한도입니다.'},429);store().addItem(u.id,'run','AI 카드 생성',{});
 const result=await generateText(u.id,`제공 자료로 한국어 카드뉴스 ${base.slides.length}장을 작성하세요. JSON만 출력: {"slides":[{"headline":"80자 이내","body":"300자 이내"}],"caption":"게시 캡션"}. 첫 장은 표지, 마지막 장은 CTA. 각 본문은 새로운 관점을 담고 사실을 지어내지 마세요.\n브랜드:${base.brief.brand}\n대상:${base.brief.audience}\n목표:${base.brief.goal}\n사용자 제작 지시:${b.instructions??''}\n${productMode()==='labs'?knowledgeContext(u.id,base.brief.brand,3000):clientContext}\n<material>${base.brief.material}</material>`);
 const clean=result.text.replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'').trim();const parsed=JSON.parse(clean);if(!Array.isArray(parsed.slides)||parsed.slides.length!==base.slides.length)throw new Error('AI 카드 장수가 맞지 않습니다. 기존 초안은 유지합니다.');
 const draft=validateDraft({...base,origin:'llmgw',slides:parsed.slides.map((s:{headline:string;body:string})=>({...s,id:randomUUID()})),caption:parsed.caption,workStatus:'draft'});return json({draft,provider:result.provider,model:result.model,cost:result.cost});
 }catch(e){return json({error:e instanceof Error?e.message:'AI 생성 실패'},400);}
}
