import path from 'node:path';
/** Root of all Cora data; same rule as store() and the legacy video renderer. */
export const dataRoot = () => process.env.CORA_DATA_DIR || path.join(process.cwd(), 'data', 'cora');
/** Ids are UUIDs generated by the server; refuse anything else before it reaches a file path. */
export const safeId = (value: string) => { if (typeof value !== 'string' || !/^[A-Za-z0-9-]{8,64}$/.test(value)) throw new Error('잘못된 식별자입니다.'); return value; };
/** CORA_DATA_DIR/<userId>/video/<sub> */
export const userVideoDir = (userId: string, sub: 'audio' | 'sources' | 'clips') => path.join(dataRoot(), safeId(userId), 'video', sub);
