from pathlib import Path
from markdown_it import MarkdownIt
import html, json
out=Path('outputs/사업전략_2026-09-29')
md=MarkdownIt('commonmark',{'html':False}).enable('table')
docs=[('개인·계정 운영','개인계정_성장지원과_콘텐츠추천_설계.md'),('BM·실행 계획','BM_평가와_구체실행계획.md'),('경쟁 전략','경쟁에서_이기는_진입전략.md'),('종합 판단','사업판정과_제품방향.md'),('실행 보충','실행인력과_8주검증계획.md'),('헌법','프로젝트헌법_제안.md'),('해외','해외기업_근거와해석.md'),('한국','한국시장_경쟁과기회.md'),('Rita','Rita_자산과연결판단.md'),('검증범위','읽는순서와_검증범위.md')]
nav=''.join(f'<button data-doc="d{i}" aria-pressed="{str(i==0).lower()}">{label}</button>' for i,(label,file) in enumerate(docs))
body=''.join(f'<article id="d{i}" {"" if i==0 else "hidden"}><a class="download" href="{html.escape(file)}">문서 원본</a>'+md.render((out/file).read_text())+'</article>' for i,(_,file) in enumerate(docs))
page='''<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>콘텐츠 운영 서비스 · 사업 방향 검토</title><style>
:root{color-scheme:light;--ink:#183138;--muted:#60757b;--line:#d6e1e1;--accent:#075a57;--bg:#f3f7f6}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:16px/1.8 -apple-system,BlinkMacSystemFont,'Apple SD Gothic Neo','Noto Sans KR',sans-serif}header,main,nav{max-width:1120px;margin:auto}header{padding:48px 28px 24px}.eyebrow{font-size:13px;letter-spacing:.08em;font-weight:700;color:var(--accent)}header h1{font-size:clamp(28px,4vw,44px);line-height:1.3;max-width:880px}header p{max-width:820px;color:var(--muted)}.verdict{background:#e3eeea;border-left:5px solid var(--accent);padding:18px 24px;margin-top:28px}.verdict strong{display:block}nav{padding:10px 28px;display:flex;gap:6px;flex-wrap:wrap;position:sticky;top:0;background:#f3f7f6f5;z-index:2;border-bottom:1px solid var(--line)}button{font:inherit;border:1px solid var(--line);background:white;padding:7px 15px;border-radius:7px;cursor:pointer}button[aria-pressed=true]{background:var(--accent);color:white;border-color:var(--accent)}main{padding:24px 28px 80px}article,#calc{background:white;border:1px solid var(--line);padding:32px;border-radius:12px}article h1{font-size:30px;line-height:1.45}article h2{font-size:23px;margin-top:44px;border-top:1px solid var(--line);padding-top:24px}article h3{font-size:19px;margin-top:30px}article p{max-width:940px}article table{display:block;overflow:auto;border-collapse:collapse;margin:22px 0;font-size:14px;line-height:1.65}th,td{padding:12px 14px;border:1px solid var(--line);text-align:left;min-width:110px;vertical-align:top}th{background:#edf3f1}a{color:#087268;text-underline-offset:3px}blockquote{border-left:4px solid var(--accent);margin:20px 0;padding:10px 22px;background:#f1f6f4}pre{overflow:auto;padding:20px;background:#edf3f2}code{font-size:13px}.download{float:right;font-size:13px}.calcgrid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}label{display:block;color:var(--muted);font-size:14px}input{display:block;width:100%;padding:10px;border:1px solid #a9bebc;border-radius:5px;font-size:18px;color:var(--ink)}.outgrid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin:24px 0}.metric{padding:18px;background:#edf3f1;border-radius:8px}.metric span{font-size:13px;display:block}.metric strong{font-size:24px;display:block}.note{font-size:14px;color:var(--muted)}.bad{color:#a53d34}.fine{color:#08604f}[hidden]{display:none!important}@media(max-width:700px){header,main{padding-left:16px;padding-right:16px}article,#calc{padding:20px}.calcgrid,.outgrid{grid-template-columns:1fr 1fr}nav{padding:8px 16px}article h1{font-size:25px}}@media print{nav,header,#calc,.download{display:none!important}article{display:block!important;border:0;padding:0;break-before:page}main{padding:0}body{font-size:11pt}a{color:inherit}}
</style><header><div class="eyebrow">2026.09.29 · 개인 계정·대행사 공통 제품 설계</div><h1>내 계정을 이해하고,<br>다음 콘텐츠를 고르고 완성한다.</h1><p>소재 발굴·제작·편집·발행·성과를 연결한다. 첫 대행사 고객군을 유지하면서, 자기 계정을 시작하고 키우는 개인 운영자도 초기 경험과 비교 검증에 포함한다.</p><div class="verdict"><strong>계정 분석에서 이번 주 추천으로, 추천에서 실제 제작으로 이어지는 서비스를 설계한다.</strong>공식 Instagram 분석은 Business/Creator 계정과 승인된 권한 범위에서 제공한다. 실제 계정 연동·성장 효과·유료 반복은 아직 검증하지 않았다. BM 가격·원가·일정은 제안이며 추가 기능에 따라 재산정한다.</div></header><nav>NAV<button data-doc="calc" aria-pressed="false">가정 계산기</button></nav><main>BODY
<section id="calc" hidden><h1>인력·비용·사업 규모를 가정으로 비교한다</h1><p>이 계산기는 견적·매출 예측·성공 확률이 아니다. 모든 단가와 운영 가정은 실제 자료로 교체해야 한다. 인건비 미입력은 무료로 확정했다는 뜻이 아니다.</p><h2>8주 검증에 필요한 시간과 현금</h2><div class="calcgrid">
<label>학생 수<input id="people" type="number" min="1" max="10" value="2"></label><label>1인당 주간 시간<input id="hours" type="number" min="0" max="40" step="0.5" value="4.5"></label><label>주 수<input id="weeks" type="number" min="1" max="52" value="8"></label><label>시간당 학생 보수 가정 (원)<input id="wage" type="number" min="0" step="1000" value="0"></label><label>디자인 외주 견적 입력 (원)<input id="design" type="number" min="0" step="10000" value="0"></label><label>추가 기술·모집 실비 한도 (원)<input id="cash" type="number" min="0" step="10000" value="300000"></label></div><div class="outgrid"><div class="metric"><span>학생 총 가용 시간</span><strong id="totalHours"></strong></div><div class="metric"><span>학생 보수 계산</span><strong id="labor"></strong></div><div class="metric"><span>입력 항목의 현금 합계</span><strong id="cashTotal"></strong></div></div><p class="note" id="missing"></p><p class="note">사용자 본인의 시간, 기존 구독비 등은 합계에서 제외되어 있다. 미입력 항목을 확인하기 전 총사업비로 사용하지 않는다.</p>
<h2>고객당 얼마가 남는가</h2><p class="note">월 구독 사업이 검증됐다고 가정한 산술 예시다. 현재 판매가·원가가 아니다. 첫 시험 납품의 5만원 가격 가설과 다른 계산이다.</p><div class="calcgrid">
<label>월 매출 / 고객 (원)<input id="price" type="number" min="0" step="10000" value="390000"></label><label>월 실행·저장 직접비 / 고객 (원)<input id="direct" type="number" min="0" step="10000" value="60000"></label><label>결제비 비율 (%)<input id="fee" type="number" min="0" max="100" value="3"></label><label>월 반복 지원 시간 / 고객<input id="support" type="number" min="0" step="0.5" value="1"></label><label>지원 노동 시간당 원가 (원)<input id="rate" type="number" min="0" step="1000" value="40000"></label><label>월 고정비 가정 (원)<input id="fixed" type="number" min="0" step="1000000" value="20000000"></label><label>유료 고객 수 가정<input id="customers" type="number" min="0" step="10" value="100"></label><label>고객 1곳 획득·초기 설정 비용 (원)<input id="acq" type="number" min="0" step="10000" value="300000"></label></div><div class="outgrid"><div class="metric"><span>고객당 월 기여이익</span><strong id="contribution"></strong></div><div class="metric"><span>기여이익률</span><strong id="margin"></strong></div><div class="metric"><span>가정한 고정비 충당 고객 수</span><strong id="breakeven"></strong></div><div class="metric"><span>연 매출 산술</span><strong id="annual"></strong></div><div class="metric"><span>월 기여이익 합계 − 고정비</span><strong id="balance"></strong></div><div class="metric"><span>획득·설정 비용 회수 기간</span><strong id="payback"></strong></div></div><p class="note">기여이익 = 매출 − 실행·저장비 − 결제비 − 반복 지원 노동. 환불·세금·누락 원가가 있으면 추가해야 한다. 월 잔액은 순이익 예측이 아니다. 회수 기간은 이탈·변동이 없다는 단순 가정이며 실제 갱신 관측을 대체하지 않는다.</p><button id="heavy">지원이 월 6시간일 때 보기</button> <button id="reset">기본 가정으로 되돌리기</button></section></main>
<script>
const $=s=>document.querySelector(s);document.querySelectorAll('[data-doc]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('article,#calc').forEach(x=>x.hidden=x.id!==b.dataset.doc);document.querySelectorAll('[data-doc]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));window.scrollTo({top:$('nav').offsetTop,behavior:'smooth'})}));
const inputs=[...document.querySelectorAll('input')], defaults=Object.fromEntries(inputs.map(x=>[x.id,x.value]));
const n=id=>Math.max(0,Number($('#'+id).value)||0), won=v=>Math.round(v).toLocaleString('ko-KR')+'원';
function calc(){const h=n('people')*n('hours')*n('weeks'),labor=h*n('wage');$('#totalHours').textContent=h.toLocaleString('ko-KR')+'시간';$('#labor').textContent=won(labor);$('#cashTotal').textContent=won(labor+n('design')+n('cash'));$('#missing').textContent=(n('wage')===0||n('design')===0)?'학생 보수 또는 디자인 견적이 0으로 입력되어 있다. 미확정 비용을 포함하면 합계가 늘어날 수 있다.':'입력값에 따른 산술 합계다. 실제 지급·계약 조건을 별도로 확인한다.';const p=n('price'),c=p-n('direct')-p*Math.min(100,n('fee'))/100-n('support')*n('rate');$('#contribution').textContent=won(c);$('#contribution').className=c>0?'fine':'bad';$('#margin').textContent=p>0?(100*c/p).toFixed(1)+'%':'계산 불가';$('#breakeven').textContent=c>0?Math.ceil(n('fixed')/c).toLocaleString('ko-KR')+'곳':'손익분기 불가';$('#annual').textContent=won(p*n('customers')*12);$('#balance').textContent=won(c*n('customers')-n('fixed'));$('#payback').textContent=c>0?(n('acq')/c).toFixed(1)+'개월':'회수 불가';}
inputs.forEach(x=>x.addEventListener('input',calc));$('#heavy').onclick=()=>{$('#support').value=6;calc()};$('#reset').onclick=()=>{inputs.forEach(x=>x.value=defaults[x.id]);calc()};calc();
</script></html>'''
page=page.replace('NAV',nav).replace('BODY',body)
(out/'전략검토.html').write_text(page)
print('HTML bytes',len(page.encode()))
