# -*- coding: utf-8 -*-
from pathlib import Path
from markdown_it import MarkdownIt

out = Path('outputs/사업전략_2026-09-29')
md = MarkdownIt('commonmark', {'html': False}).enable('table')
body = md.render((out/'BM_평가와_구체실행계획.md').read_text())
page = '''<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>대행사 콘텐츠 서비스 · BM과 실행 계획</title><style>
:root{color-scheme:light;--ink:#152d38;--muted:#536870;--bg:#f4f7f8;--line:#d5e1e3;--accent:#06615f}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:16px/1.8 -apple-system,BlinkMacSystemFont,'Apple SD Gothic Neo',sans-serif}header,main{max-width:1180px;margin:auto;padding:30px}header{padding-top:48px}.eyebrow{font-size:13px;font-weight:700;color:var(--accent)}h1{font-size:clamp(28px,4vw,43px);line-height:1.35}h2{font-size:25px;margin-top:36px}h3{font-size:20px}a{color:var(--accent);text-underline-offset:3px}.lead{max-width:880px;font-size:19px}.note{color:var(--muted);font-size:14px}.banner{padding:18px 22px;background:#e3efeb;border-left:4px solid var(--accent)}.card{padding:28px;background:white;border:1px solid var(--line);border-radius:12px;margin-bottom:24px}.presets{display:flex;gap:8px;flex-wrap:wrap}.presets button{border:1px solid var(--line);padding:10px 16px;background:white;border-radius:6px;font:inherit;cursor:pointer}.presets button[aria-pressed=true]{background:var(--accent);color:white}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin:22px 0}label{font-size:14px;color:var(--muted)}input,select{display:block;width:100%;margin-top:5px;padding:10px;border:1px solid #a8bcbf;border-radius:6px;font:inherit;color:var(--ink);background:white}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:26px}.metric{padding:18px;background:#edf4f2;border-radius:8px}.metric span{display:block;font-size:13px}.metric strong{display:block;font-size:27px;line-height:1.6}.metric small{font-size:12px;color:var(--muted)}.bad{color:#a63324}.good{color:#065c4e}details{border-top:1px solid var(--line);padding-top:12px;margin-top:20px}summary{cursor:pointer;font-weight:600}article h1{font-size:29px}article h2{border-top:1px solid var(--line);padding-top:20px;margin-top:42px;font-size:23px}table{display:block;overflow:auto;border-collapse:collapse;font-size:14px;line-height:1.7;margin:20px 0}td,th{border:1px solid var(--line);padding:10px 13px;min-width:100px;vertical-align:top}th{background:#edf4f2;text-align:left}p,li{overflow-wrap:anywhere}article p{max-width:1000px}nav{display:flex;gap:18px;flex-wrap:wrap;margin:18px 0}blockquote{border-left:4px solid var(--accent);padding:8px 20px;margin-left:0;background:#f0f5f3}@media(max-width:720px){header,main{padding:20px}.card{padding:18px}.grid,.metrics{grid-template-columns:1fr 1fr}.metric strong{font-size:22px}}@media(max-width:460px){.grid,.metrics{grid-template-columns:1fr}}@media print{#calculator,header nav{display:none}body{font-size:11pt;background:white}.card{border:0;padding:0}main{padding:0}h2{break-after:avoid}}
</style><header><div class="eyebrow">2026.09.29 · 상품·가격·고객 확보·손익·8주 실행</div><h1>대행사가 매달 구매하고,<br>고객이 늘수록 이익이 남는가.</h1><p class="lead">첫 상품은 브랜드 자료로 카드뉴스와 캡션을 직접 제작·수정하는 도구다. 단일 브랜드로 시작하고, 여러 브랜드를 운영하는 대행사 구독으로 확장한다.</p><div class="banner"><strong>제안: 1브랜드 월 59,000원 → 3브랜드 월 149,000원.</strong><br>가격·원가는 검증 전 가정이다. 사람의 대신 제작은 별도 상품으로 평가한다. 모든 손익은 부가세 제외 기준이다.</div><nav><a href="#calculator">손익 가정 바꾸기</a><a href="#report">전체 BM·실행 계획</a><a href="BM_평가와_구체실행계획.md">문서 원본</a><a href="전략검토.html">기존 조사와 경쟁 전략</a></nav></header>
<main><section class="card" id="calculator"><h2>고객의 이득과 우리의 이익을 함께 본다</h2><p class="note">실측·견적·매출 예측이 아닌 계산 도구다. 사용량은 성공적으로 사용 가능한 세트이며, 세트당 원가에는 실패·재시도·포함 AI 수정의 비용도 배분한다.</p>
<div class="presets"><button data-plan="solo" aria-pressed="false">1브랜드 · 59,000원</button><button data-plan="agency" aria-pressed="true">3브랜드 · 149,000원</button></div>
<div class="grid"><label>월 이용료 가정 (원)<input id="price" type="number" min="0" step="1000" value="149000"></label><label>실제 월 제작량 (세트)<input id="qty" type="number" min="0" step="1" value="30"></label><label>세트당 절약하는 시간 (분)<input id="saved" type="number" min="0" step="1" value="20"></label><label>고객 시간의 가치 (원/시간)<input id="customerWage" type="number" min="0" step="1000" value="30000"></label><label>고객 도입비의 월 배분 (원)<input id="customerSetup" type="number" min="0" step="1000" value="30000"></label><label>우리 원가 시나리오<select id="scenario"><option value="low">자동화가 잘된 상태</option><option value="mid" selected>중간 가정</option><option value="high">재시도·보정이 많은 상태</option></select></label></div>
<details open><summary>실행·지원·획득비 가정</summary><div class="grid"><label>실패·수정 포함 세트당 원가 (원)<input id="unit" type="number" min="0" step="100" value="1200"></label><label>월 지원·보정 시간 (분)<input id="support" type="number" min="0" step="5" value="45"></label><label>우리 노동 가치 (원/시간)<input id="ourWage" type="number" min="0" step="1000" value="30000"></label><label>고객당 인프라 배분 (원)<input id="infra" type="number" min="0" step="1000" value="6000"></label><label>결제 수수료 가정 (%)<input id="fee" type="number" min="0" max="100" step="0.1" value="3"></label><label>신규 고객 획득비 (원)<input id="cac" type="number" min="0" step="10000" value="200000"></label><label>우리의 최초 설정·교육비 (원)<input id="setup" type="number" min="0" step="5000" value="45000"></label><label>월 고정비 가정 (원)<input id="fixed" type="number" min="0" step="100000" value="5000000"></label></div></details>
<div class="metrics" aria-live="polite"><div class="metric"><span>고객에게 남는 월 가치</span><strong id="benefit"></strong><small>절약시간 가치 − 요금 − 도입비 배분</small></div><div class="metric"><span>우리 월 직접 기여이익</span><strong id="contribution"></strong><small id="margin"></small></div><div class="metric"><span>획득·설정비 회수기간</span><strong id="payback"></strong><small>같은 월 기여이익과 고객 유지 가정</small></div><div class="metric"><span>고정비 충당에 필요한 고객</span><strong id="breakeven"></strong><small>신규 획득·설정·이탈 대체 비용 제외</small></div><div class="metric"><span>월 반복 직접비</span><strong id="cost"></strong><small>실행 + 지원 + 인프라 + 결제</small></div><div class="metric"><span>고객이 절약하는 시간</span><strong id="savedHours"></strong><small>자동으로 현금 절감이 되는 것은 아님</small></div></div><p class="note" id="interpretation"></p><p class="note">직접 기여이익은 순이익이 아니다. 최초 서버 총액, 고정 개발·영업비, 환불·세금 등과 실제 지급 조건은 별도로 확인해야 한다. 고객 가치는 품질 악화가 없다는 조건이며 실제 지불 의사를 증명하지 않는다. 제작량을 포함 한도보다 높게 입력하면 요금·지원 범위도 함께 조정해야 한다.</p></section>
<article class="card" id="report">REPORT</article></main><script>
const $=id=>document.getElementById(id), value=id=>Math.max(0,Number($(id).value)||0), money=n=>Math.round(n).toLocaleString('ko-KR')+'원';
function calculate(){const p=value('price'),q=value('qty'),savedHours=q*value('saved')/60,benefit=savedHours*value('customerWage')-p-value('customerSetup'),cost=q*value('unit')+value('support')/60*value('ourWage')+value('infra')+p*Math.min(value('fee'),100)/100,c=p-cost,margin=p?c/p*100:null,pay=c>0?(value('cac')+value('setup'))/c:null,be=c>0?Math.ceil(value('fixed')/c):null;return{p,q,savedHours,benefit,cost,c,margin,pay,be};}
function render(){const m=calculate();$('benefit').textContent=money(m.benefit);$('contribution').textContent=money(m.c);$('margin').textContent=m.margin===null?'매출 0원: 기여율 계산 불가':'직접 기여율 '+m.margin.toFixed(1)+'%';$('payback').textContent=m.pay===null?'회수 불가':m.pay.toFixed(1)+'개월';$('breakeven').textContent=m.be===null?'성립 안 함':m.be.toLocaleString('ko-KR')+'곳';$('cost').textContent=money(m.cost);$('savedHours').textContent=m.savedHours.toFixed(1)+'시간';$('benefit').className=m.benefit>0?'good':'bad';$('contribution').className=m.c>0?'good':'bad';$('interpretation').textContent=m.c<=0?'이 가정에서는 고객이 늘수록 반복 직접 손실이 커진다. 가격·원가·지원 범위를 바꿔야 한다.':m.benefit<=0?'우리에게 이익이 남더라도, 이 가정에서는 고객에게 요금과 도입비를 넘는 시간 가치가 남지 않는다. 실제 추가 품질 가치 또는 다른 제안이 필요하다.':'산술상 양쪽에 가치가 남는다. 실제 품질·지불·갱신·획득비가 확인된 것은 아니다.';}
document.querySelectorAll('input').forEach(i=>i.addEventListener('input',render));document.querySelectorAll('[data-plan]').forEach(b=>b.addEventListener('click',()=>{const solo=b.dataset.plan==='solo';$('price').value=solo?59000:149000;$('qty').value=solo?10:30;document.querySelectorAll('[data-plan]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));render();}));$('scenario').addEventListener('change',()=>{const s={low:[600,15,4000],mid:[1200,45,6000],high:[2500,180,8000]}[$('scenario').value];['unit','support','infra'].forEach((id,i)=>$(id).value=s[i]);render();});render();
</script></html>'''
(out/'BM_의사결정.html').write_text(page.replace('REPORT',body))
print('BM HTML saved', (out/'BM_의사결정.html').stat().st_size)
